#!/usr/bin/env python3
"""
Add or update GPL-2 copyright headers on Go source files.
Skips pkg/model/ (autogenerated).
Uses git log to determine the file's first-commit year.

Run from the repository root (the directory this script lives in).
"""

import datetime
import os
import re
import subprocess
import sys

CURRENT_YEAR = datetime.date.today().year
OWNER = "SUSE LLC"

HEADER_TEMPLATE = """\
/*
 * Copyright (c) {years} {owner}
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see
 * <https://www.gnu.org/licenses/>
 */
"""

COPYRIGHT_RE = re.compile(
    r'(Copyright \(c\) )(\d{4})(?:-(\d{4}))?( ' + re.escape(OWNER) + r')'
)


def git_first_year(root, filepath):
    rel = os.path.relpath(filepath, root)
    try:
        result = subprocess.run(
            ["git", "log", "--follow", "--diff-filter=A", "--format=%ai", "--", rel],
            cwd=root,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            universal_newlines=True,
            check=True,
        )
        line = result.stdout.strip()
        if not line:
            print(f"WARNING: no git history for {rel}, using {CURRENT_YEAR}", file=sys.stderr)
            return CURRENT_YEAR
        return int(line[:4])
    except Exception as e:
        print(f"WARNING: git log failed for {rel}: {e}", file=sys.stderr)
        return CURRENT_YEAR


def years_string(first_year):
    if first_year >= CURRENT_YEAR:
        return str(CURRENT_YEAR)
    return f"{first_year}-{CURRENT_YEAR}"


def update_year(m):
    prefix = m.group(1)
    start_year = int(m.group(2))
    end_year = int(m.group(3)) if m.group(3) else start_year
    suffix = m.group(4)
    if end_year >= CURRENT_YEAR:
        return m.group(0)  # already current
    return f"{prefix}{years_string(start_year)}{suffix}"


def update_copyright_year(filepath, content, dry_run):
    new_content, _ = COPYRIGHT_RE.subn(update_year, content)
    if new_content == content:
        return "ok"
    if not dry_run:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(new_content)
    return "updated-year"


def add_copyright_header(filepath, content, root, dry_run):
    first_year = git_first_year(root, filepath)
    header = HEADER_TEMPLATE.format(years=years_string(first_year), owner=OWNER)
    if not dry_run:
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(header + "\n" + content)
    return "added"


def process_file(filepath, root, dry_run):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()

    for line in content.splitlines():
        if "Copyright (c)" in line and OWNER in line:
            return update_copyright_year(filepath, content, dry_run)

    return add_copyright_header(filepath, content, root, dry_run)


def find_go_files(root):
    for dirpath, dirnames, filenames in os.walk(root):
        rel = os.path.relpath(dirpath, root)
        if rel.startswith("pkg/model"):
            dirnames.clear()
            continue
        for name in filenames:
            if name.endswith(".go"):
                yield os.path.join(dirpath, name)


def main():
    dry_run = "--dry-run" in sys.argv
    root = os.path.dirname(os.path.abspath(__file__))

    counts = {"ok": 0, "updated-year": 0, "added": 0}
    for filepath in sorted(find_go_files(root)):
        status = process_file(filepath, root, dry_run)
        counts[status] += 1
        rel = os.path.relpath(filepath, root)
        if status != "ok":
            tag = "[DRY]" if dry_run else "    "
            print(f"{tag} {status:14s} {rel}")

    prefix = "(dry run) " if dry_run else ""
    print(f"\n{prefix}ok={counts['ok']}  added={counts['added']}  updated-year={counts['updated-year']}")


if __name__ == "__main__":
    main()
