/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostList{}

// HostList struct for HostList
type HostList struct {
	Items []HostListItem `json:"items"`
	Page Page `json:"page"`
	// total number of host items in all the result pages
	Total int32 `json:"total"`
}

type _HostList HostList

// NewHostList instantiates a new HostList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostList(items []HostListItem, page Page, total int32) *HostList {
	this := HostList{}
	this.Items = items
	this.Page = page
	this.Total = total
	return &this
}

// NewHostListWithDefaults instantiates a new HostList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostListWithDefaults() *HostList {
	this := HostList{}
	return &this
}

// GetItems returns the Items field value
func (o *HostList) GetItems() []HostListItem {
	if o == nil {
		var ret []HostListItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *HostList) GetItemsOk() ([]HostListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *HostList) SetItems(v []HostListItem) {
	o.Items = v
}

// GetPage returns the Page field value
func (o *HostList) GetPage() Page {
	if o == nil {
		var ret Page
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *HostList) GetPageOk() (*Page, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *HostList) SetPage(v Page) {
	o.Page = v
}

// GetTotal returns the Total field value
func (o *HostList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *HostList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *HostList) SetTotal(v int32) {
	o.Total = v
}

func (o HostList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["page"] = o.Page
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *HostList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"page",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostList := _HostList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostList)

	if err != nil {
		return err
	}

	*o = HostList(varHostList)

	return err
}

type NullableHostList struct {
	value *HostList
	isSet bool
}

func (v NullableHostList) Get() *HostList {
	return v.value
}

func (v *NullableHostList) Set(val *HostList) {
	v.value = val
	v.isSet = true
}

func (v NullableHostList) IsSet() bool {
	return v.isSet
}

func (v *NullableHostList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostList(val *HostList) *NullableHostList {
	return &NullableHostList{value: val, isSet: true}
}

func (v NullableHostList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


