/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Net type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Net{}

// Net struct for Net
type Net struct {
	Name string `json:"name"`
	Nettype NetType `json:"nettype"`
	Model NetModel `json:"model"`
	Mac string `json:"mac"`
}

type _Net Net

// NewNet instantiates a new Net object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNet(name string, nettype NetType, model NetModel, mac string) *Net {
	this := Net{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Name = name
	this.Nettype = nettype
	this.Model = model
	this.Mac = mac
	return &this
}

// NewNetWithDefaults instantiates a new Net object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetWithDefaults() *Net {
	this := Net{}
	return &this
}

// GetName returns the Name field value
func (o *Net) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Net) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Net) SetName(v string) {
	o.Name = v
}

// GetNettype returns the Nettype field value
func (o *Net) GetNettype() NetType {
	if o == nil {
		var ret NetType
		return ret
	}

	return o.Nettype
}

// GetNettypeOk returns a tuple with the Nettype field value
// and a boolean to check if the value has been set.
func (o *Net) GetNettypeOk() (*NetType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nettype, true
}

// SetNettype sets field value
func (o *Net) SetNettype(v NetType) {
	o.Nettype = v
}

// GetModel returns the Model field value
func (o *Net) GetModel() NetModel {
	if o == nil {
		var ret NetModel
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *Net) GetModelOk() (*NetModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *Net) SetModel(v NetModel) {
	o.Model = v
}

// GetMac returns the Mac field value
func (o *Net) GetMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mac
}

// GetMacOk returns a tuple with the Mac field value
// and a boolean to check if the value has been set.
func (o *Net) GetMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mac, true
}

// SetMac sets field value
func (o *Net) SetMac(v string) {
	o.Mac = v
}

func (o Net) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["nettype"] = o.Nettype
	toSerialize["model"] = o.Model
	toSerialize["mac"] = o.Mac
	return toSerialize, nil
}

type NullableNet struct {
	value *Net
	isSet bool
}

func (v NullableNet) Get() *Net {
	return v.value
}

func (v *NullableNet) Set(val *Net) {
	v.value = val
	v.isSet = true
}

func (v NullableNet) IsSet() bool {
	return v.isSet
}

func (v *NullableNet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNet(val *Net) *NullableNet {
	return &NullableNet{value: val, isSet: true}
}

func (v NullableNet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


