/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OplogList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OplogList{}

// OplogList struct for OplogList
type OplogList struct {
	Items []OplogItem `json:"items"`
}

type _OplogList OplogList

// NewOplogList instantiates a new OplogList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOplogList(items []OplogItem) *OplogList {
	this := OplogList{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Items = items
	return &this
}

// NewOplogListWithDefaults instantiates a new OplogList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOplogListWithDefaults() *OplogList {
	this := OplogList{}
	return &this
}

// GetItems returns the Items field value
func (o *OplogList) GetItems() []OplogItem {
	if o == nil {
		var ret []OplogItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *OplogList) GetItemsOk() ([]OplogItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *OplogList) SetItems(v []OplogItem) {
	o.Items = v
}

func (o OplogList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableOplogList struct {
	value *OplogList
	isSet bool
}

func (v NullableOplogList) Get() *OplogList {
	return v.value
}

func (v *NullableOplogList) Set(val *OplogList) {
	v.value = val
	v.isSet = true
}

func (v NullableOplogList) IsSet() bool {
	return v.isSet
}

func (v *NullableOplogList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOplogList(val *OplogList) *NullableOplogList {
	return &NullableOplogList{value: val, isSet: true}
}

func (v NullableOplogList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOplogList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


