/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmShutdownOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmShutdownOptions{}

// VmShutdownOptions struct for VmShutdownOptions
type VmShutdownOptions struct {
	// if true, destroy the vm immediately without any graceful shutdown (not recommended).
	Force bool `json:"force"`
}

type _VmShutdownOptions VmShutdownOptions

// NewVmShutdownOptions instantiates a new VmShutdownOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmShutdownOptions(force bool) *VmShutdownOptions {
	this := VmShutdownOptions{}
	this.Force = force
	return &this
}

// NewVmShutdownOptionsWithDefaults instantiates a new VmShutdownOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmShutdownOptionsWithDefaults() *VmShutdownOptions {
	this := VmShutdownOptions{}
	return &this
}

// GetForce returns the Force field value
func (o *VmShutdownOptions) GetForce() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Force
}

// GetForceOk returns a tuple with the Force field value
// and a boolean to check if the value has been set.
func (o *VmShutdownOptions) GetForceOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Force, true
}

// SetForce sets field value
func (o *VmShutdownOptions) SetForce(v bool) {
	o.Force = v
}

func (o VmShutdownOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmShutdownOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["force"] = o.Force
	return toSerialize, nil
}

func (o *VmShutdownOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"force",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmShutdownOptions := _VmShutdownOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmShutdownOptions)

	if err != nil {
		return err
	}

	*o = VmShutdownOptions(varVmShutdownOptions)

	return err
}

type NullableVmShutdownOptions struct {
	value *VmShutdownOptions
	isSet bool
}

func (v NullableVmShutdownOptions) Get() *VmShutdownOptions {
	return v.value
}

func (v *NullableVmShutdownOptions) Set(val *VmShutdownOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmShutdownOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmShutdownOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmShutdownOptions(val *VmShutdownOptions) *NullableVmShutdownOptions {
	return &NullableVmShutdownOptions{value: val, isSet: true}
}

func (v NullableVmShutdownOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmShutdownOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


