/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Vmruninfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vmruninfo{}

// Vmruninfo struct for Vmruninfo
type Vmruninfo struct {
	State Vmrunstate `json:"state"`
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Host string `json:"host"`
}

type _Vmruninfo Vmruninfo

// NewVmruninfo instantiates a new Vmruninfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmruninfo(state Vmrunstate, host string) *Vmruninfo {
	this := Vmruninfo{}
	this.State = state
	this.Host = host
	return &this
}

// NewVmruninfoWithDefaults instantiates a new Vmruninfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmruninfoWithDefaults() *Vmruninfo {
	this := Vmruninfo{}
	return &this
}

// GetState returns the State field value
func (o *Vmruninfo) GetState() Vmrunstate {
	if o == nil {
		var ret Vmrunstate
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Vmruninfo) GetStateOk() (*Vmrunstate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Vmruninfo) SetState(v Vmrunstate) {
	o.State = v
}

// GetHost returns the Host field value
func (o *Vmruninfo) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *Vmruninfo) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *Vmruninfo) SetHost(v string) {
	o.Host = v
}

func (o Vmruninfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vmruninfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["host"] = o.Host
	return toSerialize, nil
}

func (o *Vmruninfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
		"host",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmruninfo := _Vmruninfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmruninfo)

	if err != nil {
		return err
	}

	*o = Vmruninfo(varVmruninfo)

	return err
}

type NullableVmruninfo struct {
	value *Vmruninfo
	isSet bool
}

func (v NullableVmruninfo) Get() *Vmruninfo {
	return v.value
}

func (v *NullableVmruninfo) Set(val *Vmruninfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVmruninfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVmruninfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmruninfo(val *Vmruninfo) *NullableVmruninfo {
	return &NullableVmruninfo{value: val, isSet: true}
}

func (v NullableVmruninfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmruninfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


