/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Cstate this is the host state in the cluster (serf)
type Cstate int16

// List of cstate
const (
	CSTATE_INVALID Cstate = 0
	CSTATE_ACTIVE Cstate = 1
	CSTATE_LEFT Cstate = 2
	CSTATE_FAILED Cstate = 3
)

// All allowed values of Cstate enum
var AllowedCstateEnumValues = []Cstate{
	0,
	1,
	2,
	3,
}

func (v *Cstate) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Cstate(value)
	for _, existing := range AllowedCstateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Cstate", value)
}

// NewCstateFromValue returns a pointer to a valid Cstate
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCstateFromValue(v int16) (*Cstate, error) {
	ev := Cstate(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Cstate: valid values are %v", v, AllowedCstateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Cstate) IsValid() bool {
	for _, existing := range AllowedCstateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to cstate value
func (v Cstate) Ptr() *Cstate {
	return &v
}

type NullableCstate struct {
	value *Cstate
	isSet bool
}

func (v NullableCstate) Get() *Cstate {
	return v.value
}

func (v *NullableCstate) Set(val *Cstate) {
	v.value = val
	v.isSet = true
}

func (v NullableCstate) IsSet() bool {
	return v.isSet
}

func (v *NullableCstate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCstate(val *Cstate) *NullableCstate {
	return &NullableCstate{value: val, isSet: true}
}

func (v NullableCstate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCstate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

