/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmOplogListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmOplogListOptions{}

// VmOplogListOptions struct for VmOplogListOptions
type VmOplogListOptions struct {
	// filter to a single operation code (see x-opcode); 0 = all operations, merged chronologically
	Op int16 `json:"op"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	From int64 `json:"from"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	To int64 `json:"to"`
	// return only the last N records in range; 0 = no limit. Mutually exclusive with head.
	Tail int32 `json:"tail"`
	// return only the first N records in range; 0 = no limit. Mutually exclusive with tail.
	Head int32 `json:"head"`
	// false = chronological (oldest first); true = reverse chronological (newest first)
	Reverse bool `json:"reverse"`
}

type _VmOplogListOptions VmOplogListOptions

// NewVmOplogListOptions instantiates a new VmOplogListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmOplogListOptions(op int16, from int64, to int64, tail int32, head int32, reverse bool) *VmOplogListOptions {
	this := VmOplogListOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Op = op
	this.From = from
	this.To = to
	this.Tail = tail
	this.Head = head
	this.Reverse = reverse
	return &this
}

// NewVmOplogListOptionsWithDefaults instantiates a new VmOplogListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmOplogListOptionsWithDefaults() *VmOplogListOptions {
	this := VmOplogListOptions{}
	return &this
}

// GetOp returns the Op field value
func (o *VmOplogListOptions) GetOp() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *VmOplogListOptions) GetOpOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *VmOplogListOptions) SetOp(v int16) {
	o.Op = v
}

// GetFrom returns the From field value
func (o *VmOplogListOptions) GetFrom() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *VmOplogListOptions) GetFromOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *VmOplogListOptions) SetFrom(v int64) {
	o.From = v
}

// GetTo returns the To field value
func (o *VmOplogListOptions) GetTo() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *VmOplogListOptions) GetToOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *VmOplogListOptions) SetTo(v int64) {
	o.To = v
}

// GetTail returns the Tail field value
func (o *VmOplogListOptions) GetTail() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Tail
}

// GetTailOk returns a tuple with the Tail field value
// and a boolean to check if the value has been set.
func (o *VmOplogListOptions) GetTailOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tail, true
}

// SetTail sets field value
func (o *VmOplogListOptions) SetTail(v int32) {
	o.Tail = v
}

// GetHead returns the Head field value
func (o *VmOplogListOptions) GetHead() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Head
}

// GetHeadOk returns a tuple with the Head field value
// and a boolean to check if the value has been set.
func (o *VmOplogListOptions) GetHeadOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Head, true
}

// SetHead sets field value
func (o *VmOplogListOptions) SetHead(v int32) {
	o.Head = v
}

// GetReverse returns the Reverse field value
func (o *VmOplogListOptions) GetReverse() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Reverse
}

// GetReverseOk returns a tuple with the Reverse field value
// and a boolean to check if the value has been set.
func (o *VmOplogListOptions) GetReverseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reverse, true
}

// SetReverse sets field value
func (o *VmOplogListOptions) SetReverse(v bool) {
	o.Reverse = v
}

func (o VmOplogListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["op"] = o.Op
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["tail"] = o.Tail
	toSerialize["head"] = o.Head
	toSerialize["reverse"] = o.Reverse
	return toSerialize, nil
}

type NullableVmOplogListOptions struct {
	value *VmOplogListOptions
	isSet bool
}

func (v NullableVmOplogListOptions) Get() *VmOplogListOptions {
	return v.value
}

func (v *NullableVmOplogListOptions) Set(val *VmOplogListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmOplogListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmOplogListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmOplogListOptions(val *VmOplogListOptions) *NullableVmOplogListOptions {
	return &NullableVmOplogListOptions{value: val, isSet: true}
}

func (v NullableVmOplogListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmOplogListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


