/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Cpuarch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cpuarch{}

// Cpuarch struct for Cpuarch
type Cpuarch struct {
	// the CPU base architecture
	Arch NullableInt32 `json:"arch,omitempty"`
	// vendor as per libvirt definition, x86_vendors.xml, arm_vendors.xml
	Vendor NullableInt32 `json:"vendor,omitempty"`
}

// NewCpuarch instantiates a new Cpuarch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpuarch() *Cpuarch {
	this := Cpuarch{}
	return &this
}

// NewCpuarchWithDefaults instantiates a new Cpuarch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpuarchWithDefaults() *Cpuarch {
	this := Cpuarch{}
	return &this
}

// GetArch returns the Arch field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cpuarch) GetArch() int32 {
	if o == nil || IsNil(o.Arch.Get()) {
		var ret int32
		return ret
	}
	return *o.Arch.Get()
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cpuarch) GetArchOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Arch.Get(), o.Arch.IsSet()
}

// HasArch returns a boolean if a field has been set.
func (o *Cpuarch) HasArch() bool {
	if o != nil && o.Arch.IsSet() {
		return true
	}

	return false
}

// SetArch gets a reference to the given NullableInt32 and assigns it to the Arch field.
func (o *Cpuarch) SetArch(v int32) {
	o.Arch.Set(&v)
}
// SetArchNil sets the value for Arch to be an explicit nil
func (o *Cpuarch) SetArchNil() {
	o.Arch.Set(nil)
}

// UnsetArch ensures that no value is present for Arch, not even an explicit nil
func (o *Cpuarch) UnsetArch() {
	o.Arch.Unset()
}

// GetVendor returns the Vendor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Cpuarch) GetVendor() int32 {
	if o == nil || IsNil(o.Vendor.Get()) {
		var ret int32
		return ret
	}
	return *o.Vendor.Get()
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Cpuarch) GetVendorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vendor.Get(), o.Vendor.IsSet()
}

// HasVendor returns a boolean if a field has been set.
func (o *Cpuarch) HasVendor() bool {
	if o != nil && o.Vendor.IsSet() {
		return true
	}

	return false
}

// SetVendor gets a reference to the given NullableInt32 and assigns it to the Vendor field.
func (o *Cpuarch) SetVendor(v int32) {
	o.Vendor.Set(&v)
}
// SetVendorNil sets the value for Vendor to be an explicit nil
func (o *Cpuarch) SetVendorNil() {
	o.Vendor.Set(nil)
}

// UnsetVendor ensures that no value is present for Vendor, not even an explicit nil
func (o *Cpuarch) UnsetVendor() {
	o.Vendor.Unset()
}

func (o Cpuarch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cpuarch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Arch.IsSet() {
		toSerialize["arch"] = o.Arch.Get()
	}
	if o.Vendor.IsSet() {
		toSerialize["vendor"] = o.Vendor.Get()
	}
	return toSerialize, nil
}

type NullableCpuarch struct {
	value *Cpuarch
	isSet bool
}

func (v NullableCpuarch) Get() *Cpuarch {
	return v.value
}

func (v *NullableCpuarch) Set(val *Cpuarch) {
	v.value = val
	v.isSet = true
}

func (v NullableCpuarch) IsSet() bool {
	return v.isSet
}

func (v *NullableCpuarch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpuarch(val *Cpuarch) *NullableCpuarch {
	return &NullableCpuarch{value: val, isSet: true}
}

func (v NullableCpuarch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpuarch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


