/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Hostresources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Hostresources{}

// Hostresources Memory resources in GiB, CPU resources in MhZ
type Hostresources struct {
	Memory Hostresource `json:"memory"`
	Cpu Hostresource `json:"cpu"`
}

type _Hostresources Hostresources

// NewHostresources instantiates a new Hostresources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostresources(memory Hostresource, cpu Hostresource) *Hostresources {
	this := Hostresources{}
	this.Memory = memory
	this.Cpu = cpu
	return &this
}

// NewHostresourcesWithDefaults instantiates a new Hostresources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostresourcesWithDefaults() *Hostresources {
	this := Hostresources{}
	return &this
}

// GetMemory returns the Memory field value
func (o *Hostresources) GetMemory() Hostresource {
	if o == nil {
		var ret Hostresource
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *Hostresources) GetMemoryOk() (*Hostresource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memory, true
}

// SetMemory sets field value
func (o *Hostresources) SetMemory(v Hostresource) {
	o.Memory = v
}

// GetCpu returns the Cpu field value
func (o *Hostresources) GetCpu() Hostresource {
	if o == nil {
		var ret Hostresource
		return ret
	}

	return o.Cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *Hostresources) GetCpuOk() (*Hostresource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpu, true
}

// SetCpu sets field value
func (o *Hostresources) SetCpu(v Hostresource) {
	o.Cpu = v
}

func (o Hostresources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Hostresources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["memory"] = o.Memory
	toSerialize["cpu"] = o.Cpu
	return toSerialize, nil
}

func (o *Hostresources) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"memory",
		"cpu",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostresources := _Hostresources{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostresources)

	if err != nil {
		return err
	}

	*o = Hostresources(varHostresources)

	return err
}

type NullableHostresources struct {
	value *Hostresources
	isSet bool
}

func (v NullableHostresources) Get() *Hostresources {
	return v.value
}

func (v *NullableHostresources) Set(val *Hostresources) {
	v.value = val
	v.isSet = true
}

func (v NullableHostresources) IsSet() bool {
	return v.isSet
}

func (v *NullableHostresources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostresources(val *Hostresources) *NullableHostresources {
	return &NullableHostresources{value: val, isSet: true}
}

func (v NullableHostresources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostresources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


