/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Vmrunstate The run state of the VM
type Vmrunstate int16

// List of vmrunstate
const (
	RUNSTATE_NONE Vmrunstate = 0
	RUNSTATE_POWEROFF Vmrunstate = 1
	RUNSTATE_STARTUP Vmrunstate = 2
	RUNSTATE_RUNNING Vmrunstate = 3
	RUNSTATE_PAUSED Vmrunstate = 4
	RUNSTATE_MIGRATING Vmrunstate = 5
	RUNSTATE_TERMINATING Vmrunstate = 6
	RUNSTATE_PMSUSPENDED Vmrunstate = 7
	RUNSTATE_CRASHED Vmrunstate = 8
)

// All allowed values of Vmrunstate enum
var AllowedVmrunstateEnumValues = []Vmrunstate{
	0,
	1,
	2,
	3,
	4,
	5,
	6,
	7,
	8,
}

func (v *Vmrunstate) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Vmrunstate(value)
	for _, existing := range AllowedVmrunstateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Vmrunstate", value)
}

// NewVmrunstateFromValue returns a pointer to a valid Vmrunstate
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVmrunstateFromValue(v int16) (*Vmrunstate, error) {
	ev := Vmrunstate(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Vmrunstate: valid values are %v", v, AllowedVmrunstateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Vmrunstate) IsValid() bool {
	for _, existing := range AllowedVmrunstateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to vmrunstate value
func (v Vmrunstate) Ptr() *Vmrunstate {
	return &v
}

type NullableVmrunstate struct {
	value *Vmrunstate
	isSet bool
}

func (v NullableVmrunstate) Get() *Vmrunstate {
	return v.value
}

func (v *NullableVmrunstate) Set(val *Vmrunstate) {
	v.value = val
	v.isSet = true
}

func (v NullableVmrunstate) IsSet() bool {
	return v.isSet
}

func (v *NullableVmrunstate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmrunstate(val *Vmrunstate) *NullableVmrunstate {
	return &NullableVmrunstate{value: val, isSet: true}
}

func (v NullableVmrunstate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmrunstate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

