/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the HostListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostListItem{}

// HostListItem struct for HostListItem
type HostListItem struct {
	// Unique Identifier for VMs, Hosts, Cluster, RFC 4122
	Uuid *string `json:"uuid,omitempty"`
	Fields *HostListFields `json:"fields,omitempty"`
}

// NewHostListItem instantiates a new HostListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostListItem() *HostListItem {
	this := HostListItem{}
	return &this
}

// NewHostListItemWithDefaults instantiates a new HostListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostListItemWithDefaults() *HostListItem {
	this := HostListItem{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *HostListItem) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostListItem) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *HostListItem) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *HostListItem) SetUuid(v string) {
	o.Uuid = &v
}

// GetFields returns the Fields field value if set, zero value otherwise.
func (o *HostListItem) GetFields() HostListFields {
	if o == nil || IsNil(o.Fields) {
		var ret HostListFields
		return ret
	}
	return *o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HostListItem) GetFieldsOk() (*HostListFields, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// HasFields returns a boolean if a field has been set.
func (o *HostListItem) HasFields() bool {
	if o != nil && !IsNil(o.Fields) {
		return true
	}

	return false
}

// SetFields gets a reference to the given HostListFields and assigns it to the Fields field.
func (o *HostListItem) SetFields(v HostListFields) {
	o.Fields = &v
}

func (o HostListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Fields) {
		toSerialize["fields"] = o.Fields
	}
	return toSerialize, nil
}

type NullableHostListItem struct {
	value *HostListItem
	isSet bool
}

func (v NullableHostListItem) Get() *HostListItem {
	return v.value
}

func (v *NullableHostListItem) Set(val *HostListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableHostListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableHostListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostListItem(val *HostListItem) *NullableHostListItem {
	return &NullableHostListItem{value: val, isSet: true}
}

func (v NullableHostListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


