/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CloudInitOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CloudInitOption{}

// CloudInitOption struct for CloudInitOption
type CloudInitOption struct {
	Name string `json:"name"`
	Value string `json:"value"`
}

type _CloudInitOption CloudInitOption

// NewCloudInitOption instantiates a new CloudInitOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCloudInitOption(name string, value string) *CloudInitOption {
	this := CloudInitOption{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Name = name
	this.Value = value
	return &this
}

// NewCloudInitOptionWithDefaults instantiates a new CloudInitOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCloudInitOptionWithDefaults() *CloudInitOption {
	this := CloudInitOption{}
	return &this
}

// GetName returns the Name field value
func (o *CloudInitOption) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CloudInitOption) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CloudInitOption) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *CloudInitOption) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CloudInitOption) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *CloudInitOption) SetValue(v string) {
	o.Value = v
}

func (o CloudInitOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableCloudInitOption struct {
	value *CloudInitOption
	isSet bool
}

func (v NullableCloudInitOption) Get() *CloudInitOption {
	return v.value
}

func (v *NullableCloudInitOption) Set(val *CloudInitOption) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudInitOption) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudInitOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudInitOption(val *CloudInitOption) *NullableCloudInitOption {
	return &NullableCloudInitOption{value: val, isSet: true}
}

func (v NullableCloudInitOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudInitOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


