/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Vmruninfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vmruninfo{}

// Vmruninfo struct for Vmruninfo
type Vmruninfo struct {
	Runstate Vmrunstate `json:"runstate"`
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Host string `json:"host"`
}

type _Vmruninfo Vmruninfo

// NewVmruninfo instantiates a new Vmruninfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmruninfo(runstate Vmrunstate, host string) *Vmruninfo {
	this := Vmruninfo{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Runstate = runstate
	this.Host = host
	return &this
}

// NewVmruninfoWithDefaults instantiates a new Vmruninfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmruninfoWithDefaults() *Vmruninfo {
	this := Vmruninfo{}
	return &this
}

// GetRunstate returns the Runstate field value
func (o *Vmruninfo) GetRunstate() Vmrunstate {
	if o == nil {
		var ret Vmrunstate
		return ret
	}

	return o.Runstate
}

// GetRunstateOk returns a tuple with the Runstate field value
// and a boolean to check if the value has been set.
func (o *Vmruninfo) GetRunstateOk() (*Vmrunstate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runstate, true
}

// SetRunstate sets field value
func (o *Vmruninfo) SetRunstate(v Vmrunstate) {
	o.Runstate = v
}

// GetHost returns the Host field value
func (o *Vmruninfo) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *Vmruninfo) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *Vmruninfo) SetHost(v string) {
	o.Host = v
}

func (o Vmruninfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["runstate"] = o.Runstate
	toSerialize["host"] = o.Host
	return toSerialize, nil
}

type NullableVmruninfo struct {
	value *Vmruninfo
	isSet bool
}

func (v NullableVmruninfo) Get() *Vmruninfo {
	return v.value
}

func (v *NullableVmruninfo) Set(val *Vmruninfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVmruninfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVmruninfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmruninfo(val *Vmruninfo) *NullableVmruninfo {
	return &NullableVmruninfo{value: val, isSet: true}
}

func (v NullableVmruninfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmruninfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


