/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmMigrateInfoProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmMigrateInfoProgress{}

// VmMigrateInfoProgress struct for VmMigrateInfoProgress
type VmMigrateInfoProgress struct {
	// MiB of RAM to be trasferred
	Total *int64 `json:"total,omitempty"`
	// MiB already transferred to the migration target
	Transferred *int64 `json:"transferred,omitempty"`
	// MiB remaining to be transferred to the target
	Remaining *int64 `json:"remaining,omitempty"`
	// MiB per second. Only available for \"active\" and \"completed\"
	Rate *float32 `json:"rate,omitempty"`
}

// NewVmMigrateInfoProgress instantiates a new VmMigrateInfoProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmMigrateInfoProgress() *VmMigrateInfoProgress {
	this := VmMigrateInfoProgress{}
	return &this
}

// NewVmMigrateInfoProgressWithDefaults instantiates a new VmMigrateInfoProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmMigrateInfoProgressWithDefaults() *VmMigrateInfoProgress {
	this := VmMigrateInfoProgress{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *VmMigrateInfoProgress) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *VmMigrateInfoProgress) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *VmMigrateInfoProgress) SetTotal(v int64) {
	o.Total = &v
}

// GetTransferred returns the Transferred field value if set, zero value otherwise.
func (o *VmMigrateInfoProgress) GetTransferred() int64 {
	if o == nil || IsNil(o.Transferred) {
		var ret int64
		return ret
	}
	return *o.Transferred
}

// GetTransferredOk returns a tuple with the Transferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetTransferredOk() (*int64, bool) {
	if o == nil || IsNil(o.Transferred) {
		return nil, false
	}
	return o.Transferred, true
}

// HasTransferred returns a boolean if a field has been set.
func (o *VmMigrateInfoProgress) HasTransferred() bool {
	if o != nil && !IsNil(o.Transferred) {
		return true
	}

	return false
}

// SetTransferred gets a reference to the given int64 and assigns it to the Transferred field.
func (o *VmMigrateInfoProgress) SetTransferred(v int64) {
	o.Transferred = &v
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *VmMigrateInfoProgress) GetRemaining() int64 {
	if o == nil || IsNil(o.Remaining) {
		var ret int64
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetRemainingOk() (*int64, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *VmMigrateInfoProgress) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given int64 and assigns it to the Remaining field.
func (o *VmMigrateInfoProgress) SetRemaining(v int64) {
	o.Remaining = &v
}

// GetRate returns the Rate field value if set, zero value otherwise.
func (o *VmMigrateInfoProgress) GetRate() float32 {
	if o == nil || IsNil(o.Rate) {
		var ret float32
		return ret
	}
	return *o.Rate
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetRateOk() (*float32, bool) {
	if o == nil || IsNil(o.Rate) {
		return nil, false
	}
	return o.Rate, true
}

// HasRate returns a boolean if a field has been set.
func (o *VmMigrateInfoProgress) HasRate() bool {
	if o != nil && !IsNil(o.Rate) {
		return true
	}

	return false
}

// SetRate gets a reference to the given float32 and assigns it to the Rate field.
func (o *VmMigrateInfoProgress) SetRate(v float32) {
	o.Rate = &v
}

func (o VmMigrateInfoProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmMigrateInfoProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Transferred) {
		toSerialize["transferred"] = o.Transferred
	}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	if !IsNil(o.Rate) {
		toSerialize["rate"] = o.Rate
	}
	return toSerialize, nil
}

type NullableVmMigrateInfoProgress struct {
	value *VmMigrateInfoProgress
	isSet bool
}

func (v NullableVmMigrateInfoProgress) Get() *VmMigrateInfoProgress {
	return v.value
}

func (v *NullableVmMigrateInfoProgress) Set(val *VmMigrateInfoProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableVmMigrateInfoProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableVmMigrateInfoProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmMigrateInfoProgress(val *VmMigrateInfoProgress) *NullableVmMigrateInfoProgress {
	return &NullableVmMigrateInfoProgress{value: val, isSet: true}
}

func (v NullableVmMigrateInfoProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmMigrateInfoProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


