/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmBootOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmBootOptions{}

// VmBootOptions struct for VmBootOptions
type VmBootOptions struct {
	// ci-userdata, ci-metadata and ci-networkconfig content for a NoCloud cloud-init datasource. Content should be raw, NOT base64-encoded. ci-metadata is optional; if omitted, a minimal ci-metadata is generated automatically using the VM name as instance-id and local-hostname. 
	CloudInit []CloudInitOption `json:"cloud_init"`
}

type _VmBootOptions VmBootOptions

// NewVmBootOptions instantiates a new VmBootOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmBootOptions(cloudInit []CloudInitOption) *VmBootOptions {
	this := VmBootOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.CloudInit = cloudInit
	return &this
}

// NewVmBootOptionsWithDefaults instantiates a new VmBootOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmBootOptionsWithDefaults() *VmBootOptions {
	this := VmBootOptions{}
	return &this
}

// GetCloudInit returns the CloudInit field value
func (o *VmBootOptions) GetCloudInit() []CloudInitOption {
	if o == nil {
		var ret []CloudInitOption
		return ret
	}

	return o.CloudInit
}

// GetCloudInitOk returns a tuple with the CloudInit field value
// and a boolean to check if the value has been set.
func (o *VmBootOptions) GetCloudInitOk() ([]CloudInitOption, bool) {
	if o == nil {
		return nil, false
	}
	return o.CloudInit, true
}

// SetCloudInit sets field value
func (o *VmBootOptions) SetCloudInit(v []CloudInitOption) {
	o.CloudInit = v
}

func (o VmBootOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloud_init"] = o.CloudInit
	return toSerialize, nil
}

type NullableVmBootOptions struct {
	value *VmBootOptions
	isSet bool
}

func (v NullableVmBootOptions) Get() *VmBootOptions {
	return v.value
}

func (v *NullableVmBootOptions) Set(val *VmBootOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmBootOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmBootOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmBootOptions(val *VmBootOptions) *NullableVmBootOptions {
	return &NullableVmBootOptions{value: val, isSet: true}
}

func (v NullableVmBootOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmBootOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


