/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmdefMemory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmdefMemory{}

// VmdefMemory struct for VmdefMemory
type VmdefMemory struct {
	// total memory to reserve for the guest in MiB
	Total *int64 `json:"total,omitempty"`
}

// NewVmdefMemory instantiates a new VmdefMemory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmdefMemory() *VmdefMemory {
	this := VmdefMemory{}
	return &this
}

// NewVmdefMemoryWithDefaults instantiates a new VmdefMemory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmdefMemoryWithDefaults() *VmdefMemory {
	this := VmdefMemory{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *VmdefMemory) GetTotal() int64 {
	if o == nil || IsNil(o.Total) {
		var ret int64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmdefMemory) GetTotalOk() (*int64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *VmdefMemory) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int64 and assigns it to the Total field.
func (o *VmdefMemory) SetTotal(v int64) {
	o.Total = &v
}

func (o VmdefMemory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmdefMemory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableVmdefMemory struct {
	value *VmdefMemory
	isSet bool
}

func (v NullableVmdefMemory) Get() *VmdefMemory {
	return v.value
}

func (v *NullableVmdefMemory) Set(val *VmdefMemory) {
	v.value = val
	v.isSet = true
}

func (v NullableVmdefMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableVmdefMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmdefMemory(val *VmdefMemory) *NullableVmdefMemory {
	return &NullableVmdefMemory{value: val, isSet: true}
}

func (v NullableVmdefMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmdefMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


