/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Hostresources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Hostresources{}

// Hostresources struct for Hostresources
type Hostresources struct {
	Memory *Hostresource `json:"memory,omitempty"`
	Mhz *Hostresource `json:"mhz,omitempty"`
}

// NewHostresources instantiates a new Hostresources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostresources() *Hostresources {
	this := Hostresources{}
	return &this
}

// NewHostresourcesWithDefaults instantiates a new Hostresources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostresourcesWithDefaults() *Hostresources {
	this := Hostresources{}
	return &this
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *Hostresources) GetMemory() Hostresource {
	if o == nil || IsNil(o.Memory) {
		var ret Hostresource
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hostresources) GetMemoryOk() (*Hostresource, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *Hostresources) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given Hostresource and assigns it to the Memory field.
func (o *Hostresources) SetMemory(v Hostresource) {
	o.Memory = &v
}

// GetMhz returns the Mhz field value if set, zero value otherwise.
func (o *Hostresources) GetMhz() Hostresource {
	if o == nil || IsNil(o.Mhz) {
		var ret Hostresource
		return ret
	}
	return *o.Mhz
}

// GetMhzOk returns a tuple with the Mhz field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Hostresources) GetMhzOk() (*Hostresource, bool) {
	if o == nil || IsNil(o.Mhz) {
		return nil, false
	}
	return o.Mhz, true
}

// HasMhz returns a boolean if a field has been set.
func (o *Hostresources) HasMhz() bool {
	if o != nil && !IsNil(o.Mhz) {
		return true
	}

	return false
}

// SetMhz gets a reference to the given Hostresource and assigns it to the Mhz field.
func (o *Hostresources) SetMhz(v Hostresource) {
	o.Mhz = &v
}

func (o Hostresources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Hostresources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	if !IsNil(o.Mhz) {
		toSerialize["mhz"] = o.Mhz
	}
	return toSerialize, nil
}

type NullableHostresources struct {
	value *Hostresources
	isSet bool
}

func (v NullableHostresources) Get() *Hostresources {
	return v.value
}

func (v *NullableHostresources) Set(val *Hostresources) {
	v.value = val
	v.isSet = true
}

func (v NullableHostresources) IsSet() bool {
	return v.isSet
}

func (v *NullableHostresources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostresources(val *Hostresources) *NullableHostresources {
	return &NullableHostresources{value: val, isSet: true}
}

func (v NullableHostresources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostresources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


