/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmUpdateOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmUpdateOptions{}

// VmUpdateOptions struct for VmUpdateOptions
type VmUpdateOptions struct {
	Vmdef Vmdef `json:"vmdef"`
	// if true, managed virtual disks that are not referenced anymore will be deleted
	Deletestorage bool `json:"deletestorage"`
}

type _VmUpdateOptions VmUpdateOptions

// NewVmUpdateOptions instantiates a new VmUpdateOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmUpdateOptions(vmdef Vmdef, deletestorage bool) *VmUpdateOptions {
	this := VmUpdateOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Vmdef = vmdef
	this.Deletestorage = deletestorage
	return &this
}

// NewVmUpdateOptionsWithDefaults instantiates a new VmUpdateOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmUpdateOptionsWithDefaults() *VmUpdateOptions {
	this := VmUpdateOptions{}
	return &this
}

// GetVmdef returns the Vmdef field value
func (o *VmUpdateOptions) GetVmdef() Vmdef {
	if o == nil {
		var ret Vmdef
		return ret
	}

	return o.Vmdef
}

// GetVmdefOk returns a tuple with the Vmdef field value
// and a boolean to check if the value has been set.
func (o *VmUpdateOptions) GetVmdefOk() (*Vmdef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vmdef, true
}

// SetVmdef sets field value
func (o *VmUpdateOptions) SetVmdef(v Vmdef) {
	o.Vmdef = v
}

// GetDeletestorage returns the Deletestorage field value
func (o *VmUpdateOptions) GetDeletestorage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deletestorage
}

// GetDeletestorageOk returns a tuple with the Deletestorage field value
// and a boolean to check if the value has been set.
func (o *VmUpdateOptions) GetDeletestorageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deletestorage, true
}

// SetDeletestorage sets field value
func (o *VmUpdateOptions) SetDeletestorage(v bool) {
	o.Deletestorage = v
}

func (o VmUpdateOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vmdef"] = o.Vmdef
	toSerialize["deletestorage"] = o.Deletestorage
	return toSerialize, nil
}

type NullableVmUpdateOptions struct {
	value *VmUpdateOptions
	isSet bool
}

func (v NullableVmUpdateOptions) Get() *VmUpdateOptions {
	return v.value
}

func (v *NullableVmUpdateOptions) Set(val *VmUpdateOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmUpdateOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmUpdateOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmUpdateOptions(val *VmUpdateOptions) *NullableVmUpdateOptions {
	return &NullableVmUpdateOptions{value: val, isSet: true}
}

func (v NullableVmUpdateOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmUpdateOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


