/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmDeleteOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmDeleteOptions{}

// VmDeleteOptions struct for VmDeleteOptions
type VmDeleteOptions struct {
	// if true, delete also the associated storage (disks)
	Deletestorage bool `json:"deletestorage"`
}

type _VmDeleteOptions VmDeleteOptions

// NewVmDeleteOptions instantiates a new VmDeleteOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmDeleteOptions(deletestorage bool) *VmDeleteOptions {
	this := VmDeleteOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Deletestorage = deletestorage
	return &this
}

// NewVmDeleteOptionsWithDefaults instantiates a new VmDeleteOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmDeleteOptionsWithDefaults() *VmDeleteOptions {
	this := VmDeleteOptions{}
	return &this
}

// GetDeletestorage returns the Deletestorage field value
func (o *VmDeleteOptions) GetDeletestorage() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deletestorage
}

// GetDeletestorageOk returns a tuple with the Deletestorage field value
// and a boolean to check if the value has been set.
func (o *VmDeleteOptions) GetDeletestorageOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deletestorage, true
}

// SetDeletestorage sets field value
func (o *VmDeleteOptions) SetDeletestorage(v bool) {
	o.Deletestorage = v
}

func (o VmDeleteOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deletestorage"] = o.Deletestorage
	return toSerialize, nil
}

type NullableVmDeleteOptions struct {
	value *VmDeleteOptions
	isSet bool
}

func (v NullableVmDeleteOptions) Get() *VmDeleteOptions {
	return v.value
}

func (v *NullableVmDeleteOptions) Set(val *VmDeleteOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmDeleteOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmDeleteOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmDeleteOptions(val *VmDeleteOptions) *NullableVmDeleteOptions {
	return &NullableVmDeleteOptions{value: val, isSet: true}
}

func (v NullableVmDeleteOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmDeleteOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


