/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventlogList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventlogList{}

// EventlogList struct for EventlogList
type EventlogList struct {
	Items []EventlogItem `json:"items"`
}

type _EventlogList EventlogList

// NewEventlogList instantiates a new EventlogList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventlogList(items []EventlogItem) *EventlogList {
	this := EventlogList{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Items = items
	return &this
}

// NewEventlogListWithDefaults instantiates a new EventlogList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventlogListWithDefaults() *EventlogList {
	this := EventlogList{}
	return &this
}

// GetItems returns the Items field value
func (o *EventlogList) GetItems() []EventlogItem {
	if o == nil {
		var ret []EventlogItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *EventlogList) GetItemsOk() ([]EventlogItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *EventlogList) SetItems(v []EventlogItem) {
	o.Items = v
}

func (o EventlogList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableEventlogList struct {
	value *EventlogList
	isSet bool
}

func (v NullableEventlogList) Get() *EventlogList {
	return v.value
}

func (v *NullableEventlogList) Set(val *EventlogList) {
	v.value = val
	v.isSet = true
}

func (v NullableEventlogList) IsSet() bool {
	return v.isSet
}

func (v *NullableEventlogList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventlogList(val *EventlogList) *NullableEventlogList {
	return &NullableEventlogList{value: val, isSet: true}
}

func (v NullableEventlogList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventlogList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


