/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostNet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostNet{}

// HostNet struct for HostNet
type HostNet struct {
	// IP in the management network, derived from serf. Empty until serf is reachable.
	ManagementAddr string `json:"management_addr"`
	// Network interface for the management network. Empty until serf is reachable.
	ManagementIface string `json:"management_iface"`
	// IP address in the migration network. Empty if migration_network is not configured.
	MigrationAddr string `json:"migration_addr"`
	// Network interface for the migration network. Empty if migration_network is not configured.
	MigrationIface string `json:"migration_iface"`
}

type _HostNet HostNet

// NewHostNet instantiates a new HostNet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostNet(managementAddr string, managementIface string, migrationAddr string, migrationIface string) *HostNet {
	this := HostNet{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.ManagementAddr = managementAddr
	this.ManagementIface = managementIface
	this.MigrationAddr = migrationAddr
	this.MigrationIface = migrationIface
	return &this
}

// NewHostNetWithDefaults instantiates a new HostNet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostNetWithDefaults() *HostNet {
	this := HostNet{}
	return &this
}

// GetManagementAddr returns the ManagementAddr field value
func (o *HostNet) GetManagementAddr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManagementAddr
}

// GetManagementAddrOk returns a tuple with the ManagementAddr field value
// and a boolean to check if the value has been set.
func (o *HostNet) GetManagementAddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagementAddr, true
}

// SetManagementAddr sets field value
func (o *HostNet) SetManagementAddr(v string) {
	o.ManagementAddr = v
}

// GetManagementIface returns the ManagementIface field value
func (o *HostNet) GetManagementIface() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ManagementIface
}

// GetManagementIfaceOk returns a tuple with the ManagementIface field value
// and a boolean to check if the value has been set.
func (o *HostNet) GetManagementIfaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ManagementIface, true
}

// SetManagementIface sets field value
func (o *HostNet) SetManagementIface(v string) {
	o.ManagementIface = v
}

// GetMigrationAddr returns the MigrationAddr field value
func (o *HostNet) GetMigrationAddr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MigrationAddr
}

// GetMigrationAddrOk returns a tuple with the MigrationAddr field value
// and a boolean to check if the value has been set.
func (o *HostNet) GetMigrationAddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MigrationAddr, true
}

// SetMigrationAddr sets field value
func (o *HostNet) SetMigrationAddr(v string) {
	o.MigrationAddr = v
}

// GetMigrationIface returns the MigrationIface field value
func (o *HostNet) GetMigrationIface() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MigrationIface
}

// GetMigrationIfaceOk returns a tuple with the MigrationIface field value
// and a boolean to check if the value has been set.
func (o *HostNet) GetMigrationIfaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MigrationIface, true
}

// SetMigrationIface sets field value
func (o *HostNet) SetMigrationIface(v string) {
	o.MigrationIface = v
}

func (o HostNet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["management_addr"] = o.ManagementAddr
	toSerialize["management_iface"] = o.ManagementIface
	toSerialize["migration_addr"] = o.MigrationAddr
	toSerialize["migration_iface"] = o.MigrationIface
	return toSerialize, nil
}

type NullableHostNet struct {
	value *HostNet
	isSet bool
}

func (v NullableHostNet) Get() *HostNet {
	return v.value
}

func (v *NullableHostNet) Set(val *HostNet) {
	v.value = val
	v.isSet = true
}

func (v NullableHostNet) IsSet() bool {
	return v.isSet
}

func (v *NullableHostNet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostNet(val *HostNet) *NullableHostNet {
	return &NullableHostNet{value: val, isSet: true}
}

func (v NullableHostNet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostNet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


