/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Net type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Net{}

// Net struct for Net
type Net struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Uuid string `json:"uuid"`
	Name string `json:"name"`
	NetType *NetType `json:"net_type,omitempty"`
	Model NetModel `json:"model"`
	Mac string `json:"mac"`
}

type _Net Net

// NewNet instantiates a new Net object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNet(uuid string, name string, model NetModel, mac string) *Net {
	this := Net{}
	this.Uuid = uuid
	this.Name = name
	this.Model = model
	this.Mac = mac
	return &this
}

// NewNetWithDefaults instantiates a new Net object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetWithDefaults() *Net {
	this := Net{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Net) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Net) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Net) SetUuid(v string) {
	o.Uuid = v
}

// GetName returns the Name field value
func (o *Net) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Net) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Net) SetName(v string) {
	o.Name = v
}

// GetNetType returns the NetType field value if set, zero value otherwise.
func (o *Net) GetNetType() NetType {
	if o == nil || IsNil(o.NetType) {
		var ret NetType
		return ret
	}
	return *o.NetType
}

// GetNetTypeOk returns a tuple with the NetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Net) GetNetTypeOk() (*NetType, bool) {
	if o == nil || IsNil(o.NetType) {
		return nil, false
	}
	return o.NetType, true
}

// HasNetType returns a boolean if a field has been set.
func (o *Net) HasNetType() bool {
	if o != nil && !IsNil(o.NetType) {
		return true
	}

	return false
}

// SetNetType gets a reference to the given NetType and assigns it to the NetType field.
func (o *Net) SetNetType(v NetType) {
	o.NetType = &v
}

// GetModel returns the Model field value
func (o *Net) GetModel() NetModel {
	if o == nil {
		var ret NetModel
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *Net) GetModelOk() (*NetModel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *Net) SetModel(v NetModel) {
	o.Model = v
}

// GetMac returns the Mac field value
func (o *Net) GetMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mac
}

// GetMacOk returns a tuple with the Mac field value
// and a boolean to check if the value has been set.
func (o *Net) GetMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mac, true
}

// SetMac sets field value
func (o *Net) SetMac(v string) {
	o.Mac = v
}

func (o Net) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Net) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["name"] = o.Name
	if !IsNil(o.NetType) {
		toSerialize["net_type"] = o.NetType
	}
	toSerialize["model"] = o.Model
	toSerialize["mac"] = o.Mac
	return toSerialize, nil
}

func (o *Net) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"name",
		"model",
		"mac",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNet := _Net{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNet)

	if err != nil {
		return err
	}

	*o = Net(varNet)

	return err
}

type NullableNet struct {
	value *Net
	isSet bool
}

func (v NullableNet) Get() *Net {
	return v.value
}

func (v *NullableNet) Set(val *Net) {
	v.value = val
	v.isSet = true
}

func (v NullableNet) IsSet() bool {
	return v.isSet
}

func (v *NullableNet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNet(val *Net) *NullableNet {
	return &NullableNet{value: val, isSet: true}
}

func (v NullableNet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


