/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransferProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransferProgress{}

// TransferProgress struct for TransferProgress
type TransferProgress struct {
	// MiB to be trasferred
	Total int64 `json:"total"`
	// MiB already transferred
	Transferred int64 `json:"transferred"`
	// MiB remaining to be transferred
	Remaining int64 `json:"remaining"`
	// MiB per second.
	Rate float32 `json:"rate"`
}

type _TransferProgress TransferProgress

// NewTransferProgress instantiates a new TransferProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransferProgress(total int64, transferred int64, remaining int64, rate float32) *TransferProgress {
	this := TransferProgress{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Total = total
	this.Transferred = transferred
	this.Remaining = remaining
	this.Rate = rate
	return &this
}

// NewTransferProgressWithDefaults instantiates a new TransferProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransferProgressWithDefaults() *TransferProgress {
	this := TransferProgress{}
	return &this
}

// GetTotal returns the Total field value
func (o *TransferProgress) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *TransferProgress) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *TransferProgress) SetTotal(v int64) {
	o.Total = v
}

// GetTransferred returns the Transferred field value
func (o *TransferProgress) GetTransferred() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Transferred
}

// GetTransferredOk returns a tuple with the Transferred field value
// and a boolean to check if the value has been set.
func (o *TransferProgress) GetTransferredOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transferred, true
}

// SetTransferred sets field value
func (o *TransferProgress) SetTransferred(v int64) {
	o.Transferred = v
}

// GetRemaining returns the Remaining field value
func (o *TransferProgress) GetRemaining() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value
// and a boolean to check if the value has been set.
func (o *TransferProgress) GetRemainingOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remaining, true
}

// SetRemaining sets field value
func (o *TransferProgress) SetRemaining(v int64) {
	o.Remaining = v
}

// GetRate returns the Rate field value
func (o *TransferProgress) GetRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rate
}

// GetRateOk returns a tuple with the Rate field value
// and a boolean to check if the value has been set.
func (o *TransferProgress) GetRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rate, true
}

// SetRate sets field value
func (o *TransferProgress) SetRate(v float32) {
	o.Rate = v
}

func (o TransferProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["transferred"] = o.Transferred
	toSerialize["remaining"] = o.Remaining
	toSerialize["rate"] = o.Rate
	return toSerialize, nil
}

type NullableTransferProgress struct {
	value *TransferProgress
	isSet bool
}

func (v NullableTransferProgress) Get() *TransferProgress {
	return v.value
}

func (v *NullableTransferProgress) Set(val *TransferProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableTransferProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableTransferProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransferProgress(val *TransferProgress) *NullableTransferProgress {
	return &NullableTransferProgress{value: val, isSet: true}
}

func (v NullableTransferProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransferProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


