/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmListFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmListFields{}

// VmListFields struct for VmListFields
type VmListFields struct {
	Name string `json:"name"`
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Host string `json:"host"`
	Runstate Vmrunstate `json:"runstate"`
	// vlanid for all traffic from/to this VM. 0 = no vlanid, -1 = automatically assign
	Vlanid int16 `json:"vlanid"`
	Custom CustomField `json:"custom"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Ts int64 `json:"ts"`
}

type _VmListFields VmListFields

// NewVmListFields instantiates a new VmListFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmListFields(name string, host string, runstate Vmrunstate, vlanid int16, custom CustomField, ts int64) *VmListFields {
	this := VmListFields{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Name = name
	this.Host = host
	this.Runstate = runstate
	this.Vlanid = vlanid
	this.Custom = custom
	this.Ts = ts
	return &this
}

// NewVmListFieldsWithDefaults instantiates a new VmListFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListFieldsWithDefaults() *VmListFields {
	this := VmListFields{}
	return &this
}

// GetName returns the Name field value
func (o *VmListFields) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VmListFields) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VmListFields) SetName(v string) {
	o.Name = v
}

// GetHost returns the Host field value
func (o *VmListFields) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *VmListFields) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *VmListFields) SetHost(v string) {
	o.Host = v
}

// GetRunstate returns the Runstate field value
func (o *VmListFields) GetRunstate() Vmrunstate {
	if o == nil {
		var ret Vmrunstate
		return ret
	}

	return o.Runstate
}

// GetRunstateOk returns a tuple with the Runstate field value
// and a boolean to check if the value has been set.
func (o *VmListFields) GetRunstateOk() (*Vmrunstate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runstate, true
}

// SetRunstate sets field value
func (o *VmListFields) SetRunstate(v Vmrunstate) {
	o.Runstate = v
}

// GetVlanid returns the Vlanid field value
func (o *VmListFields) GetVlanid() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Vlanid
}

// GetVlanidOk returns a tuple with the Vlanid field value
// and a boolean to check if the value has been set.
func (o *VmListFields) GetVlanidOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vlanid, true
}

// SetVlanid sets field value
func (o *VmListFields) SetVlanid(v int16) {
	o.Vlanid = v
}

// GetCustom returns the Custom field value
func (o *VmListFields) GetCustom() CustomField {
	if o == nil {
		var ret CustomField
		return ret
	}

	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value
// and a boolean to check if the value has been set.
func (o *VmListFields) GetCustomOk() (*CustomField, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Custom, true
}

// SetCustom sets field value
func (o *VmListFields) SetCustom(v CustomField) {
	o.Custom = v
}

// GetTs returns the Ts field value
func (o *VmListFields) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *VmListFields) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *VmListFields) SetTs(v int64) {
	o.Ts = v
}

func (o VmListFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["host"] = o.Host
	toSerialize["runstate"] = o.Runstate
	toSerialize["vlanid"] = o.Vlanid
	toSerialize["custom"] = o.Custom
	toSerialize["ts"] = o.Ts
	return toSerialize, nil
}

type NullableVmListFields struct {
	value *VmListFields
	isSet bool
}

func (v NullableVmListFields) Get() *VmListFields {
	return v.value
}

func (v *NullableVmListFields) Set(val *VmListFields) {
	v.value = val
	v.isSet = true
}

func (v NullableVmListFields) IsSet() bool {
	return v.isSet
}

func (v *NullableVmListFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmListFields(val *VmListFields) *NullableVmListFields {
	return &NullableVmListFields{value: val, isSet: true}
}

func (v NullableVmListFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmListFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


