/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Vm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vm{}

// Vm struct for Vm
type Vm struct {
	// Unique Identifier for VMs, Hosts, Cluster, RFC 4122
	Uuid *string `json:"uuid,omitempty"`
	Vmdef *Vmdef `json:"vmdef,omitempty"`
	Runstate *Vmruninfo `json:"runstate,omitempty"`
	Seq *int64 `json:"seq,omitempty"`
}

// NewVm instantiates a new Vm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVm() *Vm {
	this := Vm{}
	return &this
}

// NewVmWithDefaults instantiates a new Vm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmWithDefaults() *Vm {
	this := Vm{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *Vm) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vm) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *Vm) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *Vm) SetUuid(v string) {
	o.Uuid = &v
}

// GetVmdef returns the Vmdef field value if set, zero value otherwise.
func (o *Vm) GetVmdef() Vmdef {
	if o == nil || IsNil(o.Vmdef) {
		var ret Vmdef
		return ret
	}
	return *o.Vmdef
}

// GetVmdefOk returns a tuple with the Vmdef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vm) GetVmdefOk() (*Vmdef, bool) {
	if o == nil || IsNil(o.Vmdef) {
		return nil, false
	}
	return o.Vmdef, true
}

// HasVmdef returns a boolean if a field has been set.
func (o *Vm) HasVmdef() bool {
	if o != nil && !IsNil(o.Vmdef) {
		return true
	}

	return false
}

// SetVmdef gets a reference to the given Vmdef and assigns it to the Vmdef field.
func (o *Vm) SetVmdef(v Vmdef) {
	o.Vmdef = &v
}

// GetRunstate returns the Runstate field value if set, zero value otherwise.
func (o *Vm) GetRunstate() Vmruninfo {
	if o == nil || IsNil(o.Runstate) {
		var ret Vmruninfo
		return ret
	}
	return *o.Runstate
}

// GetRunstateOk returns a tuple with the Runstate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vm) GetRunstateOk() (*Vmruninfo, bool) {
	if o == nil || IsNil(o.Runstate) {
		return nil, false
	}
	return o.Runstate, true
}

// HasRunstate returns a boolean if a field has been set.
func (o *Vm) HasRunstate() bool {
	if o != nil && !IsNil(o.Runstate) {
		return true
	}

	return false
}

// SetRunstate gets a reference to the given Vmruninfo and assigns it to the Runstate field.
func (o *Vm) SetRunstate(v Vmruninfo) {
	o.Runstate = &v
}

// GetSeq returns the Seq field value if set, zero value otherwise.
func (o *Vm) GetSeq() int64 {
	if o == nil || IsNil(o.Seq) {
		var ret int64
		return ret
	}
	return *o.Seq
}

// GetSeqOk returns a tuple with the Seq field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vm) GetSeqOk() (*int64, bool) {
	if o == nil || IsNil(o.Seq) {
		return nil, false
	}
	return o.Seq, true
}

// HasSeq returns a boolean if a field has been set.
func (o *Vm) HasSeq() bool {
	if o != nil && !IsNil(o.Seq) {
		return true
	}

	return false
}

// SetSeq gets a reference to the given int64 and assigns it to the Seq field.
func (o *Vm) SetSeq(v int64) {
	o.Seq = &v
}

func (o Vm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Vmdef) {
		toSerialize["vmdef"] = o.Vmdef
	}
	if !IsNil(o.Runstate) {
		toSerialize["runstate"] = o.Runstate
	}
	if !IsNil(o.Seq) {
		toSerialize["seq"] = o.Seq
	}
	return toSerialize, nil
}

type NullableVm struct {
	value *Vm
	isSet bool
}

func (v NullableVm) Get() *Vm {
	return v.value
}

func (v *NullableVm) Set(val *Vm) {
	v.value = val
	v.isSet = true
}

func (v NullableVm) IsSet() bool {
	return v.isSet
}

func (v *NullableVm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVm(val *Vm) *NullableVm {
	return &NullableVm{value: val, isSet: true}
}

func (v NullableVm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


