/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostListFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostListFields{}

// HostListFields struct for HostListFields
type HostListFields struct {
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Ts int64 `json:"ts"`
	Name string `json:"name"`
	Cpudef Cpudef `json:"cpudef"`
	Cstate Cstate `json:"cstate"`
	// normal memory available for running new VMs in MiB
	Memavail int32 `json:"memavail"`
	// hugepages memory available for running new VMs in MiB
	Hpavail int32 `json:"hpavail"`
	Osid string `json:"osid"`
	Osv string `json:"osv"`
}

type _HostListFields HostListFields

// NewHostListFields instantiates a new HostListFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostListFields(ts int64, name string, cpudef Cpudef, cstate Cstate, memavail int32, hpavail int32, osid string, osv string) *HostListFields {
	this := HostListFields{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Ts = ts
	this.Name = name
	this.Cpudef = cpudef
	this.Cstate = cstate
	this.Memavail = memavail
	this.Hpavail = hpavail
	this.Osid = osid
	this.Osv = osv
	return &this
}

// NewHostListFieldsWithDefaults instantiates a new HostListFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostListFieldsWithDefaults() *HostListFields {
	this := HostListFields{}
	return &this
}

// GetTs returns the Ts field value
func (o *HostListFields) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *HostListFields) SetTs(v int64) {
	o.Ts = v
}

// GetName returns the Name field value
func (o *HostListFields) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HostListFields) SetName(v string) {
	o.Name = v
}

// GetCpudef returns the Cpudef field value
func (o *HostListFields) GetCpudef() Cpudef {
	if o == nil {
		var ret Cpudef
		return ret
	}

	return o.Cpudef
}

// GetCpudefOk returns a tuple with the Cpudef field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetCpudefOk() (*Cpudef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpudef, true
}

// SetCpudef sets field value
func (o *HostListFields) SetCpudef(v Cpudef) {
	o.Cpudef = v
}

// GetCstate returns the Cstate field value
func (o *HostListFields) GetCstate() Cstate {
	if o == nil {
		var ret Cstate
		return ret
	}

	return o.Cstate
}

// GetCstateOk returns a tuple with the Cstate field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetCstateOk() (*Cstate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cstate, true
}

// SetCstate sets field value
func (o *HostListFields) SetCstate(v Cstate) {
	o.Cstate = v
}

// GetMemavail returns the Memavail field value
func (o *HostListFields) GetMemavail() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Memavail
}

// GetMemavailOk returns a tuple with the Memavail field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetMemavailOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memavail, true
}

// SetMemavail sets field value
func (o *HostListFields) SetMemavail(v int32) {
	o.Memavail = v
}

// GetHpavail returns the Hpavail field value
func (o *HostListFields) GetHpavail() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Hpavail
}

// GetHpavailOk returns a tuple with the Hpavail field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetHpavailOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hpavail, true
}

// SetHpavail sets field value
func (o *HostListFields) SetHpavail(v int32) {
	o.Hpavail = v
}

// GetOsid returns the Osid field value
func (o *HostListFields) GetOsid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Osid
}

// GetOsidOk returns a tuple with the Osid field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetOsidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Osid, true
}

// SetOsid sets field value
func (o *HostListFields) SetOsid(v string) {
	o.Osid = v
}

// GetOsv returns the Osv field value
func (o *HostListFields) GetOsv() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Osv
}

// GetOsvOk returns a tuple with the Osv field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetOsvOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Osv, true
}

// SetOsv sets field value
func (o *HostListFields) SetOsv(v string) {
	o.Osv = v
}

func (o HostListFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ts"] = o.Ts
	toSerialize["name"] = o.Name
	toSerialize["cpudef"] = o.Cpudef
	toSerialize["cstate"] = o.Cstate
	toSerialize["memavail"] = o.Memavail
	toSerialize["hpavail"] = o.Hpavail
	toSerialize["osid"] = o.Osid
	toSerialize["osv"] = o.Osv
	return toSerialize, nil
}

type NullableHostListFields struct {
	value *HostListFields
	isSet bool
}

func (v NullableHostListFields) Get() *HostListFields {
	return v.value
}

func (v *NullableHostListFields) Set(val *HostListFields) {
	v.value = val
	v.isSet = true
}

func (v NullableHostListFields) IsSet() bool {
	return v.isSet
}

func (v *NullableHostListFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostListFields(val *HostListFields) *NullableHostListFields {
	return &NullableHostListFields{value: val, isSet: true}
}

func (v NullableHostListFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostListFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


