/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EventClass broad category of an event_code. PERSISTED, APPEND ONLY!
type EventClass int16

// List of event_class
const (
	EVENT_CLASS_ERROR EventClass = 1
	EVENT_CLASS_GUEST EventClass = 2
)

// All allowed values of EventClass enum
var AllowedEventClassEnumValues = []EventClass{
	1,
	2,
}

func (v *EventClass) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EventClass(value)
	for _, existing := range AllowedEventClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EventClass", value)
}

// NewEventClassFromValue returns a pointer to a valid EventClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEventClassFromValue(v int16) (*EventClass, error) {
	ev := EventClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EventClass: valid values are %v", v, AllowedEventClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EventClass) IsValid() bool {
	for _, existing := range AllowedEventClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to event_class value
func (v EventClass) Ptr() *EventClass {
	return &v
}

type NullableEventClass struct {
	value *EventClass
	isSet bool
}

func (v NullableEventClass) Get() *EventClass {
	return v.value
}

func (v *NullableEventClass) Set(val *EventClass) {
	v.value = val
	v.isSet = true
}

func (v NullableEventClass) IsSet() bool {
	return v.isSet
}

func (v *NullableEventClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventClass(val *EventClass) *NullableEventClass {
	return &NullableEventClass{value: val, isSet: true}
}

func (v NullableEventClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

