/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Vmruninfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vmruninfo{}

// Vmruninfo struct for Vmruninfo
type Vmruninfo struct {
	State *Vmrunstate `json:"state,omitempty"`
	// Unique Identifier for VMs, Hosts, Cluster, RFC 4122
	Host *string `json:"host,omitempty"`
}

// NewVmruninfo instantiates a new Vmruninfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmruninfo() *Vmruninfo {
	this := Vmruninfo{}
	return &this
}

// NewVmruninfoWithDefaults instantiates a new Vmruninfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmruninfoWithDefaults() *Vmruninfo {
	this := Vmruninfo{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *Vmruninfo) GetState() Vmrunstate {
	if o == nil || IsNil(o.State) {
		var ret Vmrunstate
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmruninfo) GetStateOk() (*Vmrunstate, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *Vmruninfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given Vmrunstate and assigns it to the State field.
func (o *Vmruninfo) SetState(v Vmrunstate) {
	o.State = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *Vmruninfo) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmruninfo) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *Vmruninfo) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *Vmruninfo) SetHost(v string) {
	o.Host = &v
}

func (o Vmruninfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vmruninfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	return toSerialize, nil
}

type NullableVmruninfo struct {
	value *Vmruninfo
	isSet bool
}

func (v NullableVmruninfo) Get() *Vmruninfo {
	return v.value
}

func (v *NullableVmruninfo) Set(val *Vmruninfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVmruninfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVmruninfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmruninfo(val *Vmruninfo) *NullableVmruninfo {
	return &NullableVmruninfo{value: val, isSet: true}
}

func (v NullableVmruninfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmruninfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


