/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmListItem{}

// VmListItem struct for VmListItem
type VmListItem struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Uuid string `json:"uuid"`
	Fields VmListFields `json:"fields"`
}

type _VmListItem VmListItem

// NewVmListItem instantiates a new VmListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmListItem(uuid string, fields VmListFields) *VmListItem {
	this := VmListItem{}
	this.Uuid = uuid
	this.Fields = fields
	return &this
}

// NewVmListItemWithDefaults instantiates a new VmListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListItemWithDefaults() *VmListItem {
	this := VmListItem{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *VmListItem) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *VmListItem) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *VmListItem) SetUuid(v string) {
	o.Uuid = v
}

// GetFields returns the Fields field value
func (o *VmListItem) GetFields() VmListFields {
	if o == nil {
		var ret VmListFields
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *VmListItem) GetFieldsOk() (*VmListFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *VmListItem) SetFields(v VmListFields) {
	o.Fields = v
}

func (o VmListItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

func (o *VmListItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"fields",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmListItem := _VmListItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmListItem)

	if err != nil {
		return err
	}

	*o = VmListItem(varVmListItem)

	return err
}

type NullableVmListItem struct {
	value *VmListItem
	isSet bool
}

func (v NullableVmListItem) Get() *VmListItem {
	return v.value
}

func (v *NullableVmListItem) Set(val *VmListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableVmListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableVmListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmListItem(val *VmListItem) *NullableVmListItem {
	return &NullableVmListItem{value: val, isSet: true}
}

func (v NullableVmListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


