/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// EventCode specific kind of VM state change not requested via the VirtX API. PERSISTED, APPEND ONLY!
type EventCode int16

// List of event_code
const (
	EVENT_WATCHDOG EventCode = 1001
	EVENT_PANIC EventCode = 1002
	EVENT_CRASH EventCode = 1003
	EVENT_STORAGE EventCode = 1004
	EVENT_MONITOR EventCode = 1005
	EVENT_MEMORY EventCode = 1006
	EVENT_SHUTDOWN EventCode = 2001
	EVENT_REBOOT EventCode = 2002
)

// All allowed values of EventCode enum
var AllowedEventCodeEnumValues = []EventCode{
	1001,
	1002,
	1003,
	1004,
	1005,
	1006,
	2001,
	2002,
}

func (v *EventCode) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EventCode(value)
	for _, existing := range AllowedEventCodeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EventCode", value)
}

// NewEventCodeFromValue returns a pointer to a valid EventCode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEventCodeFromValue(v int16) (*EventCode, error) {
	ev := EventCode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EventCode: valid values are %v", v, AllowedEventCodeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EventCode) IsValid() bool {
	for _, existing := range AllowedEventCodeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to event_code value
func (v EventCode) Ptr() *EventCode {
	return &v
}

type NullableEventCode struct {
	value *EventCode
	isSet bool
}

func (v NullableEventCode) Get() *EventCode {
	return v.value
}

func (v *NullableEventCode) Set(val *EventCode) {
	v.value = val
	v.isSet = true
}

func (v NullableEventCode) IsSet() bool {
	return v.isSet
}

func (v *NullableEventCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventCode(val *EventCode) *NullableEventCode {
	return &NullableEventCode{value: val, isSet: true}
}

func (v NullableEventCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

