/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Cpudef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cpudef{}

// Cpudef struct for Cpudef
type Cpudef struct {
	// libvirt cpu model. \"\" -> not set
	Model string `json:"model"`
	// number of NUMA nodes. 0 -> not set
	Nodes int16 `json:"nodes"`
	// number of sockets per node. 0 -> not set
	Sockets int16 `json:"sockets"`
	// number of cores per socket. 0 -> not set
	Cores int16 `json:"cores"`
	// number of threads per core. 0 -> not set
	Threads int16 `json:"threads"`
}

type _Cpudef Cpudef

// NewCpudef instantiates a new Cpudef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpudef(model string, nodes int16, sockets int16, cores int16, threads int16) *Cpudef {
	this := Cpudef{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Model = model
	this.Nodes = nodes
	this.Sockets = sockets
	this.Cores = cores
	this.Threads = threads
	return &this
}

// NewCpudefWithDefaults instantiates a new Cpudef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpudefWithDefaults() *Cpudef {
	this := Cpudef{}
	return &this
}

// GetModel returns the Model field value
func (o *Cpudef) GetModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Model
}

// GetModelOk returns a tuple with the Model field value
// and a boolean to check if the value has been set.
func (o *Cpudef) GetModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Model, true
}

// SetModel sets field value
func (o *Cpudef) SetModel(v string) {
	o.Model = v
}

// GetNodes returns the Nodes field value
func (o *Cpudef) GetNodes() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *Cpudef) GetNodesOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nodes, true
}

// SetNodes sets field value
func (o *Cpudef) SetNodes(v int16) {
	o.Nodes = v
}

// GetSockets returns the Sockets field value
func (o *Cpudef) GetSockets() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Sockets
}

// GetSocketsOk returns a tuple with the Sockets field value
// and a boolean to check if the value has been set.
func (o *Cpudef) GetSocketsOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sockets, true
}

// SetSockets sets field value
func (o *Cpudef) SetSockets(v int16) {
	o.Sockets = v
}

// GetCores returns the Cores field value
func (o *Cpudef) GetCores() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Cores
}

// GetCoresOk returns a tuple with the Cores field value
// and a boolean to check if the value has been set.
func (o *Cpudef) GetCoresOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cores, true
}

// SetCores sets field value
func (o *Cpudef) SetCores(v int16) {
	o.Cores = v
}

// GetThreads returns the Threads field value
func (o *Cpudef) GetThreads() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Threads
}

// GetThreadsOk returns a tuple with the Threads field value
// and a boolean to check if the value has been set.
func (o *Cpudef) GetThreadsOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Threads, true
}

// SetThreads sets field value
func (o *Cpudef) SetThreads(v int16) {
	o.Threads = v
}

func (o Cpudef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["model"] = o.Model
	toSerialize["nodes"] = o.Nodes
	toSerialize["sockets"] = o.Sockets
	toSerialize["cores"] = o.Cores
	toSerialize["threads"] = o.Threads
	return toSerialize, nil
}

type NullableCpudef struct {
	value *Cpudef
	isSet bool
}

func (v NullableCpudef) Get() *Cpudef {
	return v.value
}

func (v *NullableCpudef) Set(val *Cpudef) {
	v.value = val
	v.isSet = true
}

func (v NullableCpudef) IsSet() bool {
	return v.isSet
}

func (v *NullableCpudef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpudef(val *Cpudef) *NullableCpudef {
	return &NullableCpudef{value: val, isSet: true}
}

func (v NullableCpudef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpudef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


