/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmRegisterOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmRegisterOptions{}

// VmRegisterOptions struct for VmRegisterOptions
type VmRegisterOptions struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Host string `json:"host"`
}

type _VmRegisterOptions VmRegisterOptions

// NewVmRegisterOptions instantiates a new VmRegisterOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmRegisterOptions(host string) *VmRegisterOptions {
	this := VmRegisterOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Host = host
	return &this
}

// NewVmRegisterOptionsWithDefaults instantiates a new VmRegisterOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmRegisterOptionsWithDefaults() *VmRegisterOptions {
	this := VmRegisterOptions{}
	return &this
}

// GetHost returns the Host field value
func (o *VmRegisterOptions) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *VmRegisterOptions) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *VmRegisterOptions) SetHost(v string) {
	o.Host = v
}

func (o VmRegisterOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	return toSerialize, nil
}

type NullableVmRegisterOptions struct {
	value *VmRegisterOptions
	isSet bool
}

func (v NullableVmRegisterOptions) Get() *VmRegisterOptions {
	return v.value
}

func (v *NullableVmRegisterOptions) Set(val *VmRegisterOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmRegisterOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmRegisterOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmRegisterOptions(val *VmRegisterOptions) *NullableVmRegisterOptions {
	return &NullableVmRegisterOptions{value: val, isSet: true}
}

func (v NullableVmRegisterOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmRegisterOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


