/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostListFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostListFields{}

// HostListFields struct for HostListFields
type HostListFields struct {
	Name string `json:"name"`
	Cpuarch Cpuarch `json:"cpuarch"`
	Cpudef Cpudef `json:"cpudef"`
	Hoststate Hoststate `json:"hoststate"`
	// memory available for running new VMs in MiB
	Memoryavailable int32 `json:"memoryavailable"`
}

type _HostListFields HostListFields

// NewHostListFields instantiates a new HostListFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostListFields(name string, cpuarch Cpuarch, cpudef Cpudef, hoststate Hoststate, memoryavailable int32) *HostListFields {
	this := HostListFields{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Name = name
	this.Cpuarch = cpuarch
	this.Cpudef = cpudef
	this.Hoststate = hoststate
	this.Memoryavailable = memoryavailable
	return &this
}

// NewHostListFieldsWithDefaults instantiates a new HostListFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostListFieldsWithDefaults() *HostListFields {
	this := HostListFields{}
	return &this
}

// GetName returns the Name field value
func (o *HostListFields) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *HostListFields) SetName(v string) {
	o.Name = v
}

// GetCpuarch returns the Cpuarch field value
func (o *HostListFields) GetCpuarch() Cpuarch {
	if o == nil {
		var ret Cpuarch
		return ret
	}

	return o.Cpuarch
}

// GetCpuarchOk returns a tuple with the Cpuarch field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetCpuarchOk() (*Cpuarch, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpuarch, true
}

// SetCpuarch sets field value
func (o *HostListFields) SetCpuarch(v Cpuarch) {
	o.Cpuarch = v
}

// GetCpudef returns the Cpudef field value
func (o *HostListFields) GetCpudef() Cpudef {
	if o == nil {
		var ret Cpudef
		return ret
	}

	return o.Cpudef
}

// GetCpudefOk returns a tuple with the Cpudef field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetCpudefOk() (*Cpudef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpudef, true
}

// SetCpudef sets field value
func (o *HostListFields) SetCpudef(v Cpudef) {
	o.Cpudef = v
}

// GetHoststate returns the Hoststate field value
func (o *HostListFields) GetHoststate() Hoststate {
	if o == nil {
		var ret Hoststate
		return ret
	}

	return o.Hoststate
}

// GetHoststateOk returns a tuple with the Hoststate field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetHoststateOk() (*Hoststate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hoststate, true
}

// SetHoststate sets field value
func (o *HostListFields) SetHoststate(v Hoststate) {
	o.Hoststate = v
}

// GetMemoryavailable returns the Memoryavailable field value
func (o *HostListFields) GetMemoryavailable() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Memoryavailable
}

// GetMemoryavailableOk returns a tuple with the Memoryavailable field value
// and a boolean to check if the value has been set.
func (o *HostListFields) GetMemoryavailableOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memoryavailable, true
}

// SetMemoryavailable sets field value
func (o *HostListFields) SetMemoryavailable(v int32) {
	o.Memoryavailable = v
}

func (o HostListFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["cpuarch"] = o.Cpuarch
	toSerialize["cpudef"] = o.Cpudef
	toSerialize["hoststate"] = o.Hoststate
	toSerialize["memoryavailable"] = o.Memoryavailable
	return toSerialize, nil
}

type NullableHostListFields struct {
	value *HostListFields
	isSet bool
}

func (v NullableHostListFields) Get() *HostListFields {
	return v.value
}

func (v *NullableHostListFields) Set(val *HostListFields) {
	v.value = val
	v.isSet = true
}

func (v NullableHostListFields) IsSet() bool {
	return v.isSet
}

func (v *NullableHostListFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostListFields(val *HostListFields) *NullableHostListFields {
	return &NullableHostListFields{value: val, isSet: true}
}

func (v NullableHostListFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostListFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


