/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// FirmwareType BIOS or EFI to boot
type FirmwareType int16

// List of firmware_type
const (
	FIRMWARE_BIOS FirmwareType = 0
	FIRMWARE_UEFI FirmwareType = 1
)

// All allowed values of FirmwareType enum
var AllowedFirmwareTypeEnumValues = []FirmwareType{
	0,
	1,
}

func (v *FirmwareType) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := FirmwareType(value)
	for _, existing := range AllowedFirmwareTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid FirmwareType", value)
}

// NewFirmwareTypeFromValue returns a pointer to a valid FirmwareType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewFirmwareTypeFromValue(v int16) (*FirmwareType, error) {
	ev := FirmwareType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for FirmwareType: valid values are %v", v, AllowedFirmwareTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v FirmwareType) IsValid() bool {
	for _, existing := range AllowedFirmwareTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to firmware_type value
func (v FirmwareType) Ptr() *FirmwareType {
	return &v
}

type NullableFirmwareType struct {
	value *FirmwareType
	isSet bool
}

func (v NullableFirmwareType) Get() *FirmwareType {
	return v.value
}

func (v *NullableFirmwareType) Set(val *FirmwareType) {
	v.value = val
	v.isSet = true
}

func (v NullableFirmwareType) IsSet() bool {
	return v.isSet
}

func (v *NullableFirmwareType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFirmwareType(val *FirmwareType) *NullableFirmwareType {
	return &NullableFirmwareType{value: val, isSet: true}
}

func (v NullableFirmwareType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFirmwareType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

