/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DiskBus libvirt 'target' disk field, how the device appears in the guest
type DiskBus int16

// List of disk_bus
const (
	BUS_VIRTIO DiskBus = 0
	BUS_VIRTIO_SCSI DiskBus = 1
	BUS_SATA DiskBus = 2
	BUS_SCSI DiskBus = 3
)

// All allowed values of DiskBus enum
var AllowedDiskBusEnumValues = []DiskBus{
	0,
	1,
	2,
	3,
}

func (v *DiskBus) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiskBus(value)
	for _, existing := range AllowedDiskBusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiskBus", value)
}

// NewDiskBusFromValue returns a pointer to a valid DiskBus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiskBusFromValue(v int16) (*DiskBus, error) {
	ev := DiskBus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiskBus: valid values are %v", v, AllowedDiskBusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiskBus) IsValid() bool {
	for _, existing := range AllowedDiskBusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to disk_bus value
func (v DiskBus) Ptr() *DiskBus {
	return &v
}

type NullableDiskBus struct {
	value *DiskBus
	isSet bool
}

func (v NullableDiskBus) Get() *DiskBus {
	return v.value
}

func (v *NullableDiskBus) Set(val *DiskBus) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskBus) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskBus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskBus(val *DiskBus) *NullableDiskBus {
	return &NullableDiskBus{value: val, isSet: true}
}

func (v NullableDiskBus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskBus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

