/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EventlogItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventlogItem{}

// EventlogItem struct for EventlogItem
type EventlogItem struct {
	Class EventClass `json:"class"`
	Code EventCode `json:"code"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Ts int64 `json:"ts"`
	Msg string `json:"msg"`
}

type _EventlogItem EventlogItem

// NewEventlogItem instantiates a new EventlogItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventlogItem(class EventClass, code EventCode, ts int64, msg string) *EventlogItem {
	this := EventlogItem{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Class = class
	this.Code = code
	this.Ts = ts
	this.Msg = msg
	return &this
}

// NewEventlogItemWithDefaults instantiates a new EventlogItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventlogItemWithDefaults() *EventlogItem {
	this := EventlogItem{}
	return &this
}

// GetClass returns the Class field value
func (o *EventlogItem) GetClass() EventClass {
	if o == nil {
		var ret EventClass
		return ret
	}

	return o.Class
}

// GetClassOk returns a tuple with the Class field value
// and a boolean to check if the value has been set.
func (o *EventlogItem) GetClassOk() (*EventClass, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Class, true
}

// SetClass sets field value
func (o *EventlogItem) SetClass(v EventClass) {
	o.Class = v
}

// GetCode returns the Code field value
func (o *EventlogItem) GetCode() EventCode {
	if o == nil {
		var ret EventCode
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *EventlogItem) GetCodeOk() (*EventCode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *EventlogItem) SetCode(v EventCode) {
	o.Code = v
}

// GetTs returns the Ts field value
func (o *EventlogItem) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *EventlogItem) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *EventlogItem) SetTs(v int64) {
	o.Ts = v
}

// GetMsg returns the Msg field value
func (o *EventlogItem) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *EventlogItem) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *EventlogItem) SetMsg(v string) {
	o.Msg = v
}

func (o EventlogItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["class"] = o.Class
	toSerialize["code"] = o.Code
	toSerialize["ts"] = o.Ts
	toSerialize["msg"] = o.Msg
	return toSerialize, nil
}

type NullableEventlogItem struct {
	value *EventlogItem
	isSet bool
}

func (v NullableEventlogItem) Get() *EventlogItem {
	return v.value
}

func (v *NullableEventlogItem) Set(val *EventlogItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEventlogItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEventlogItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventlogItem(val *EventlogItem) *NullableEventlogItem {
	return &NullableEventlogItem{value: val, isSet: true}
}

func (v NullableEventlogItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventlogItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


