/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Vm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vm{}

// Vm struct for Vm
type Vm struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Uuid string `json:"uuid"`
	Vmdef Vmdef `json:"vmdef"`
	Runstate Vmruninfo `json:"runstate"`
	Seq int64 `json:"seq"`
}

type _Vm Vm

// NewVm instantiates a new Vm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVm(uuid string, vmdef Vmdef, runstate Vmruninfo, seq int64) *Vm {
	this := Vm{}
	this.Uuid = uuid
	this.Vmdef = vmdef
	this.Runstate = runstate
	this.Seq = seq
	return &this
}

// NewVmWithDefaults instantiates a new Vm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmWithDefaults() *Vm {
	this := Vm{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Vm) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Vm) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Vm) SetUuid(v string) {
	o.Uuid = v
}

// GetVmdef returns the Vmdef field value
func (o *Vm) GetVmdef() Vmdef {
	if o == nil {
		var ret Vmdef
		return ret
	}

	return o.Vmdef
}

// GetVmdefOk returns a tuple with the Vmdef field value
// and a boolean to check if the value has been set.
func (o *Vm) GetVmdefOk() (*Vmdef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vmdef, true
}

// SetVmdef sets field value
func (o *Vm) SetVmdef(v Vmdef) {
	o.Vmdef = v
}

// GetRunstate returns the Runstate field value
func (o *Vm) GetRunstate() Vmruninfo {
	if o == nil {
		var ret Vmruninfo
		return ret
	}

	return o.Runstate
}

// GetRunstateOk returns a tuple with the Runstate field value
// and a boolean to check if the value has been set.
func (o *Vm) GetRunstateOk() (*Vmruninfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Runstate, true
}

// SetRunstate sets field value
func (o *Vm) SetRunstate(v Vmruninfo) {
	o.Runstate = v
}

// GetSeq returns the Seq field value
func (o *Vm) GetSeq() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Seq
}

// GetSeqOk returns a tuple with the Seq field value
// and a boolean to check if the value has been set.
func (o *Vm) GetSeqOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seq, true
}

// SetSeq sets field value
func (o *Vm) SetSeq(v int64) {
	o.Seq = v
}

func (o Vm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["vmdef"] = o.Vmdef
	toSerialize["runstate"] = o.Runstate
	toSerialize["seq"] = o.Seq
	return toSerialize, nil
}

func (o *Vm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"vmdef",
		"runstate",
		"seq",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVm := _Vm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVm)

	if err != nil {
		return err
	}

	*o = Vm(varVm)

	return err
}

type NullableVm struct {
	value *Vm
	isSet bool
}

func (v NullableVm) Get() *Vm {
	return v.value
}

func (v *NullableVm) Set(val *Vm) {
	v.value = val
	v.isSet = true
}

func (v NullableVm) IsSet() bool {
	return v.isSet
}

func (v *NullableVm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVm(val *Vm) *NullableVm {
	return &NullableVm{value: val, isSet: true}
}

func (v NullableVm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


