/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// Hoststate the model 'Hoststate'
type Hoststate string

// List of hoststate
const (
	ALIVE Hoststate = "alive"
	LEFT Hoststate = "left"
	FAILED Hoststate = "failed"
)

// All allowed values of Hoststate enum
var AllowedHoststateEnumValues = []Hoststate{
	"alive",
	"left",
	"failed",
}

func (v *Hoststate) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Hoststate(value)
	for _, existing := range AllowedHoststateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Hoststate", value)
}

// NewHoststateFromValue returns a pointer to a valid Hoststate
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewHoststateFromValue(v string) (*Hoststate, error) {
	ev := Hoststate(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Hoststate: valid values are %v", v, AllowedHoststateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Hoststate) IsValid() bool {
	for _, existing := range AllowedHoststateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to hoststate value
func (v Hoststate) Ptr() *Hoststate {
	return &v
}

type NullableHoststate struct {
	value *Hoststate
	isSet bool
}

func (v NullableHoststate) Get() *Hoststate {
	return v.value
}

func (v *NullableHoststate) Set(val *Hoststate) {
	v.value = val
	v.isSet = true
}

func (v NullableHoststate) IsSet() bool {
	return v.isSet
}

func (v *NullableHoststate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHoststate(val *Hoststate) *NullableHoststate {
	return &NullableHoststate{value: val, isSet: true}
}

func (v NullableHoststate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHoststate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

