/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Host type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Host{}

// Host struct for Host
type Host struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Uuid string `json:"uuid"`
	Def Hostdef `json:"def"`
	Cstate Cstate `json:"cstate"`
	// Unique ID in the cluster used to register the lockspace.
	Lockid int16 `json:"lockid"`
	// computing resources of the host.
	Resources Hostresources `json:"resources"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Ts int64 `json:"ts"`
}

type _Host Host

// NewHost instantiates a new Host object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHost(uuid string, def Hostdef, cstate Cstate, lockid int16, resources Hostresources, ts int64) *Host {
	this := Host{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Uuid = uuid
	this.Def = def
	this.Cstate = cstate
	this.Lockid = lockid
	this.Resources = resources
	this.Ts = ts
	return &this
}

// NewHostWithDefaults instantiates a new Host object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostWithDefaults() *Host {
	this := Host{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Host) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Host) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Host) SetUuid(v string) {
	o.Uuid = v
}

// GetDef returns the Def field value
func (o *Host) GetDef() Hostdef {
	if o == nil {
		var ret Hostdef
		return ret
	}

	return o.Def
}

// GetDefOk returns a tuple with the Def field value
// and a boolean to check if the value has been set.
func (o *Host) GetDefOk() (*Hostdef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Def, true
}

// SetDef sets field value
func (o *Host) SetDef(v Hostdef) {
	o.Def = v
}

// GetCstate returns the Cstate field value
func (o *Host) GetCstate() Cstate {
	if o == nil {
		var ret Cstate
		return ret
	}

	return o.Cstate
}

// GetCstateOk returns a tuple with the Cstate field value
// and a boolean to check if the value has been set.
func (o *Host) GetCstateOk() (*Cstate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cstate, true
}

// SetCstate sets field value
func (o *Host) SetCstate(v Cstate) {
	o.Cstate = v
}

// GetLockid returns the Lockid field value
func (o *Host) GetLockid() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Lockid
}

// GetLockidOk returns a tuple with the Lockid field value
// and a boolean to check if the value has been set.
func (o *Host) GetLockidOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lockid, true
}

// SetLockid sets field value
func (o *Host) SetLockid(v int16) {
	o.Lockid = v
}

// GetResources returns the Resources field value
func (o *Host) GetResources() Hostresources {
	if o == nil {
		var ret Hostresources
		return ret
	}

	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value
// and a boolean to check if the value has been set.
func (o *Host) GetResourcesOk() (*Hostresources, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resources, true
}

// SetResources sets field value
func (o *Host) SetResources(v Hostresources) {
	o.Resources = v
}

// GetTs returns the Ts field value
func (o *Host) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *Host) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *Host) SetTs(v int64) {
	o.Ts = v
}

func (o Host) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["def"] = o.Def
	toSerialize["cstate"] = o.Cstate
	toSerialize["lockid"] = o.Lockid
	toSerialize["resources"] = o.Resources
	toSerialize["ts"] = o.Ts
	return toSerialize, nil
}

type NullableHost struct {
	value *Host
	isSet bool
}

func (v NullableHost) Get() *Host {
	return v.value
}

func (v *NullableHost) Set(val *Host) {
	v.value = val
	v.isSet = true
}

func (v NullableHost) IsSet() bool {
	return v.isSet
}

func (v *NullableHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHost(val *Host) *NullableHost {
	return &NullableHost{value: val, isSet: true}
}

func (v NullableHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


