/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmMigrateInfoProgress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmMigrateInfoProgress{}

// VmMigrateInfoProgress struct for VmMigrateInfoProgress
type VmMigrateInfoProgress struct {
	// MiB of RAM to be trasferred
	Total int64 `json:"total"`
	// MiB already transferred to the migration target
	Transferred int64 `json:"transferred"`
	// MiB remaining to be transferred to the target
	Remaining int64 `json:"remaining"`
	// MiB per second. Only available for \"active\" and \"completed\"
	Rate float32 `json:"rate"`
}

type _VmMigrateInfoProgress VmMigrateInfoProgress

// NewVmMigrateInfoProgress instantiates a new VmMigrateInfoProgress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmMigrateInfoProgress(total int64, transferred int64, remaining int64, rate float32) *VmMigrateInfoProgress {
	this := VmMigrateInfoProgress{}
	this.Total = total
	this.Transferred = transferred
	this.Remaining = remaining
	this.Rate = rate
	return &this
}

// NewVmMigrateInfoProgressWithDefaults instantiates a new VmMigrateInfoProgress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmMigrateInfoProgressWithDefaults() *VmMigrateInfoProgress {
	this := VmMigrateInfoProgress{}
	return &this
}

// GetTotal returns the Total field value
func (o *VmMigrateInfoProgress) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *VmMigrateInfoProgress) SetTotal(v int64) {
	o.Total = v
}

// GetTransferred returns the Transferred field value
func (o *VmMigrateInfoProgress) GetTransferred() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Transferred
}

// GetTransferredOk returns a tuple with the Transferred field value
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetTransferredOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transferred, true
}

// SetTransferred sets field value
func (o *VmMigrateInfoProgress) SetTransferred(v int64) {
	o.Transferred = v
}

// GetRemaining returns the Remaining field value
func (o *VmMigrateInfoProgress) GetRemaining() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetRemainingOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Remaining, true
}

// SetRemaining sets field value
func (o *VmMigrateInfoProgress) SetRemaining(v int64) {
	o.Remaining = v
}

// GetRate returns the Rate field value
func (o *VmMigrateInfoProgress) GetRate() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Rate
}

// GetRateOk returns a tuple with the Rate field value
// and a boolean to check if the value has been set.
func (o *VmMigrateInfoProgress) GetRateOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rate, true
}

// SetRate sets field value
func (o *VmMigrateInfoProgress) SetRate(v float32) {
	o.Rate = v
}

func (o VmMigrateInfoProgress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmMigrateInfoProgress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["transferred"] = o.Transferred
	toSerialize["remaining"] = o.Remaining
	toSerialize["rate"] = o.Rate
	return toSerialize, nil
}

func (o *VmMigrateInfoProgress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"total",
		"transferred",
		"remaining",
		"rate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmMigrateInfoProgress := _VmMigrateInfoProgress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmMigrateInfoProgress)

	if err != nil {
		return err
	}

	*o = VmMigrateInfoProgress(varVmMigrateInfoProgress)

	return err
}

type NullableVmMigrateInfoProgress struct {
	value *VmMigrateInfoProgress
	isSet bool
}

func (v NullableVmMigrateInfoProgress) Get() *VmMigrateInfoProgress {
	return v.value
}

func (v *NullableVmMigrateInfoProgress) Set(val *VmMigrateInfoProgress) {
	v.value = val
	v.isSet = true
}

func (v NullableVmMigrateInfoProgress) IsSet() bool {
	return v.isSet
}

func (v *NullableVmMigrateInfoProgress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmMigrateInfoProgress(val *VmMigrateInfoProgress) *NullableVmMigrateInfoProgress {
	return &NullableVmMigrateInfoProgress{value: val, isSet: true}
}

func (v NullableVmMigrateInfoProgress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmMigrateInfoProgress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


