/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmMigrateOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmMigrateOptions{}

// VmMigrateOptions struct for VmMigrateOptions
type VmMigrateOptions struct {
	// Unique Identifier for VMs, Hosts, Cluster, RFC 4122
	Host *string `json:"host,omitempty"`
}

// NewVmMigrateOptions instantiates a new VmMigrateOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmMigrateOptions() *VmMigrateOptions {
	this := VmMigrateOptions{}
	return &this
}

// NewVmMigrateOptionsWithDefaults instantiates a new VmMigrateOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmMigrateOptionsWithDefaults() *VmMigrateOptions {
	this := VmMigrateOptions{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *VmMigrateOptions) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateOptions) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *VmMigrateOptions) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *VmMigrateOptions) SetHost(v string) {
	o.Host = &v
}

func (o VmMigrateOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmMigrateOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	return toSerialize, nil
}

type NullableVmMigrateOptions struct {
	value *VmMigrateOptions
	isSet bool
}

func (v NullableVmMigrateOptions) Get() *VmMigrateOptions {
	return v.value
}

func (v *NullableVmMigrateOptions) Set(val *VmMigrateOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmMigrateOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmMigrateOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmMigrateOptions(val *VmMigrateOptions) *NullableVmMigrateOptions {
	return &NullableVmMigrateOptions{value: val, isSet: true}
}

func (v NullableVmMigrateOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmMigrateOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


