/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmdefMemory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmdefMemory{}

// VmdefMemory struct for VmdefMemory
type VmdefMemory struct {
	// total memory reserved for the guest in MiB
	Total int32 `json:"total"`
	// whether hugepages are requested
	Hp bool `json:"hp"`
}

type _VmdefMemory VmdefMemory

// NewVmdefMemory instantiates a new VmdefMemory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmdefMemory(total int32, hp bool) *VmdefMemory {
	this := VmdefMemory{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Total = total
	this.Hp = hp
	return &this
}

// NewVmdefMemoryWithDefaults instantiates a new VmdefMemory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmdefMemoryWithDefaults() *VmdefMemory {
	this := VmdefMemory{}
	return &this
}

// GetTotal returns the Total field value
func (o *VmdefMemory) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *VmdefMemory) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *VmdefMemory) SetTotal(v int32) {
	o.Total = v
}

// GetHp returns the Hp field value
func (o *VmdefMemory) GetHp() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Hp
}

// GetHpOk returns a tuple with the Hp field value
// and a boolean to check if the value has been set.
func (o *VmdefMemory) GetHpOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hp, true
}

// SetHp sets field value
func (o *VmdefMemory) SetHp(v bool) {
	o.Hp = v
}

func (o VmdefMemory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["hp"] = o.Hp
	return toSerialize, nil
}

type NullableVmdefMemory struct {
	value *VmdefMemory
	isSet bool
}

func (v NullableVmdefMemory) Get() *VmdefMemory {
	return v.value
}

func (v *NullableVmdefMemory) Set(val *VmdefMemory) {
	v.value = val
	v.isSet = true
}

func (v NullableVmdefMemory) IsSet() bool {
	return v.isSet
}

func (v *NullableVmdefMemory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmdefMemory(val *VmdefMemory) *NullableVmdefMemory {
	return &NullableVmdefMemory{value: val, isSet: true}
}

func (v NullableVmdefMemory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmdefMemory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


