/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// NetType the model 'NetType'
type NetType int16

// List of net_type
const (
	NET_LIBVIRT NetType = 0
	NET_BRIDGE NetType = 1
)

// All allowed values of NetType enum
var AllowedNetTypeEnumValues = []NetType{
	0,
	1,
}

func (v *NetType) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NetType(value)
	for _, existing := range AllowedNetTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NetType", value)
}

// NewNetTypeFromValue returns a pointer to a valid NetType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNetTypeFromValue(v int16) (*NetType, error) {
	ev := NetType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NetType: valid values are %v", v, AllowedNetTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NetType) IsValid() bool {
	for _, existing := range AllowedNetTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to net_type value
func (v NetType) Ptr() *NetType {
	return &v
}

type NullableNetType struct {
	value *NetType
	isSet bool
}

func (v NullableNetType) Get() *NetType {
	return v.value
}

func (v *NullableNetType) Set(val *NetType) {
	v.value = val
	v.isSet = true
}

func (v NullableNetType) IsSet() bool {
	return v.isSet
}

func (v *NullableNetType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetType(val *NetType) *NullableNetType {
	return &NullableNetType{value: val, isSet: true}
}

func (v NullableNetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

