/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmList{}

// VmList struct for VmList
type VmList struct {
	Items []VmListItem `json:"items,omitempty"`
	Page *Page `json:"page,omitempty"`
	// total number of vm items in all the result pages
	Total *int32 `json:"total,omitempty"`
}

// NewVmList instantiates a new VmList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmList() *VmList {
	this := VmList{}
	return &this
}

// NewVmListWithDefaults instantiates a new VmList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListWithDefaults() *VmList {
	this := VmList{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *VmList) GetItems() []VmListItem {
	if o == nil || IsNil(o.Items) {
		var ret []VmListItem
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmList) GetItemsOk() ([]VmListItem, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *VmList) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []VmListItem and assigns it to the Items field.
func (o *VmList) SetItems(v []VmListItem) {
	o.Items = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *VmList) GetPage() Page {
	if o == nil || IsNil(o.Page) {
		var ret Page
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmList) GetPageOk() (*Page, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *VmList) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given Page and assigns it to the Page field.
func (o *VmList) SetPage(v Page) {
	o.Page = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *VmList) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmList) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *VmList) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *VmList) SetTotal(v int32) {
	o.Total = &v
}

func (o VmList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableVmList struct {
	value *VmList
	isSet bool
}

func (v NullableVmList) Get() *VmList {
	return v.value
}

func (v *NullableVmList) Set(val *VmList) {
	v.value = val
	v.isSet = true
}

func (v NullableVmList) IsSet() bool {
	return v.isSet
}

func (v *NullableVmList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmList(val *VmList) *NullableVmList {
	return &NullableVmList{value: val, isSet: true}
}

func (v NullableVmList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


