/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmListOptions{}

// VmListOptions struct for VmListOptions
type VmListOptions struct {
	Filter VmListFields `json:"filter"`
}

type _VmListOptions VmListOptions

// NewVmListOptions instantiates a new VmListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmListOptions(filter VmListFields) *VmListOptions {
	this := VmListOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Filter = filter
	return &this
}

// NewVmListOptionsWithDefaults instantiates a new VmListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListOptionsWithDefaults() *VmListOptions {
	this := VmListOptions{}
	return &this
}

// GetFilter returns the Filter field value
func (o *VmListOptions) GetFilter() VmListFields {
	if o == nil {
		var ret VmListFields
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *VmListOptions) GetFilterOk() (*VmListFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *VmListOptions) SetFilter(v VmListFields) {
	o.Filter = v
}

func (o VmListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter"] = o.Filter
	return toSerialize, nil
}

type NullableVmListOptions struct {
	value *VmListOptions
	isSet bool
}

func (v NullableVmListOptions) Get() *VmListOptions {
	return v.value
}

func (v *NullableVmListOptions) Set(val *VmListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmListOptions(val *VmListOptions) *NullableVmListOptions {
	return &NullableVmListOptions{value: val, isSet: true}
}

func (v NullableVmListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


