/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmListOptions{}

// VmListOptions struct for VmListOptions
type VmListOptions struct {
	Filter *VmListFields `json:"filter,omitempty"`
	Page *Page `json:"page,omitempty"`
}

// NewVmListOptions instantiates a new VmListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmListOptions() *VmListOptions {
	this := VmListOptions{}
	return &this
}

// NewVmListOptionsWithDefaults instantiates a new VmListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListOptionsWithDefaults() *VmListOptions {
	this := VmListOptions{}
	return &this
}

// GetFilter returns the Filter field value if set, zero value otherwise.
func (o *VmListOptions) GetFilter() VmListFields {
	if o == nil || IsNil(o.Filter) {
		var ret VmListFields
		return ret
	}
	return *o.Filter
}

// GetFilterOk returns a tuple with the Filter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListOptions) GetFilterOk() (*VmListFields, bool) {
	if o == nil || IsNil(o.Filter) {
		return nil, false
	}
	return o.Filter, true
}

// HasFilter returns a boolean if a field has been set.
func (o *VmListOptions) HasFilter() bool {
	if o != nil && !IsNil(o.Filter) {
		return true
	}

	return false
}

// SetFilter gets a reference to the given VmListFields and assigns it to the Filter field.
func (o *VmListOptions) SetFilter(v VmListFields) {
	o.Filter = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *VmListOptions) GetPage() Page {
	if o == nil || IsNil(o.Page) {
		var ret Page
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListOptions) GetPageOk() (*Page, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *VmListOptions) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given Page and assigns it to the Page field.
func (o *VmListOptions) SetPage(v Page) {
	o.Page = &v
}

func (o VmListOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filter) {
		toSerialize["filter"] = o.Filter
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableVmListOptions struct {
	value *VmListOptions
	isSet bool
}

func (v NullableVmListOptions) Get() *VmListOptions {
	return v.value
}

func (v *NullableVmListOptions) Set(val *VmListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmListOptions(val *VmListOptions) *NullableVmListOptions {
	return &NullableVmListOptions{value: val, isSet: true}
}

func (v NullableVmListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


