/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LogItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogItem{}

// LogItem an operation (ts to te) or an event (te = ts, state OPERATION_NONE, no msge)
type LogItem struct {
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Ts int64 `json:"ts"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Te int64 `json:"te"`
	// an operation code (see x-opcode) or an event_code. PERSISTED!
	Code int16 `json:"code"`
	State OperationState `json:"state"`
	Msgs string `json:"msgs"`
	Msge string `json:"msge"`
}

type _LogItem LogItem

// NewLogItem instantiates a new LogItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogItem(ts int64, te int64, code int16, state OperationState, msgs string, msge string) *LogItem {
	this := LogItem{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Ts = ts
	this.Te = te
	this.Code = code
	this.State = state
	this.Msgs = msgs
	this.Msge = msge
	return &this
}

// NewLogItemWithDefaults instantiates a new LogItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogItemWithDefaults() *LogItem {
	this := LogItem{}
	return &this
}

// GetTs returns the Ts field value
func (o *LogItem) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *LogItem) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *LogItem) SetTs(v int64) {
	o.Ts = v
}

// GetTe returns the Te field value
func (o *LogItem) GetTe() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Te
}

// GetTeOk returns a tuple with the Te field value
// and a boolean to check if the value has been set.
func (o *LogItem) GetTeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Te, true
}

// SetTe sets field value
func (o *LogItem) SetTe(v int64) {
	o.Te = v
}

// GetCode returns the Code field value
func (o *LogItem) GetCode() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *LogItem) GetCodeOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *LogItem) SetCode(v int16) {
	o.Code = v
}

// GetState returns the State field value
func (o *LogItem) GetState() OperationState {
	if o == nil {
		var ret OperationState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *LogItem) GetStateOk() (*OperationState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *LogItem) SetState(v OperationState) {
	o.State = v
}

// GetMsgs returns the Msgs field value
func (o *LogItem) GetMsgs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msgs
}

// GetMsgsOk returns a tuple with the Msgs field value
// and a boolean to check if the value has been set.
func (o *LogItem) GetMsgsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msgs, true
}

// SetMsgs sets field value
func (o *LogItem) SetMsgs(v string) {
	o.Msgs = v
}

// GetMsge returns the Msge field value
func (o *LogItem) GetMsge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msge
}

// GetMsgeOk returns a tuple with the Msge field value
// and a boolean to check if the value has been set.
func (o *LogItem) GetMsgeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msge, true
}

// SetMsge sets field value
func (o *LogItem) SetMsge(v string) {
	o.Msge = v
}

func (o LogItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ts"] = o.Ts
	toSerialize["te"] = o.Te
	toSerialize["code"] = o.Code
	toSerialize["state"] = o.State
	toSerialize["msgs"] = o.Msgs
	toSerialize["msge"] = o.Msge
	return toSerialize, nil
}

type NullableLogItem struct {
	value *LogItem
	isSet bool
}

func (v NullableLogItem) Get() *LogItem {
	return v.value
}

func (v *NullableLogItem) Set(val *LogItem) {
	v.value = val
	v.isSet = true
}

func (v NullableLogItem) IsSet() bool {
	return v.isSet
}

func (v *NullableLogItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogItem(val *LogItem) *NullableLogItem {
	return &NullableLogItem{value: val, isSet: true}
}

func (v NullableLogItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


