/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostListItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostListItem{}

// HostListItem struct for HostListItem
type HostListItem struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Uuid string `json:"uuid"`
	Fields HostListFields `json:"fields"`
}

type _HostListItem HostListItem

// NewHostListItem instantiates a new HostListItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostListItem(uuid string, fields HostListFields) *HostListItem {
	this := HostListItem{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Uuid = uuid
	this.Fields = fields
	return &this
}

// NewHostListItemWithDefaults instantiates a new HostListItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostListItemWithDefaults() *HostListItem {
	this := HostListItem{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *HostListItem) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *HostListItem) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *HostListItem) SetUuid(v string) {
	o.Uuid = v
}

// GetFields returns the Fields field value
func (o *HostListItem) GetFields() HostListFields {
	if o == nil {
		var ret HostListFields
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
func (o *HostListItem) GetFieldsOk() (*HostListFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fields, true
}

// SetFields sets field value
func (o *HostListItem) SetFields(v HostListFields) {
	o.Fields = v
}

func (o HostListItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["fields"] = o.Fields
	return toSerialize, nil
}

type NullableHostListItem struct {
	value *HostListItem
	isSet bool
}

func (v NullableHostListItem) Get() *HostListItem {
	return v.value
}

func (v *NullableHostListItem) Set(val *HostListItem) {
	v.value = val
	v.isSet = true
}

func (v NullableHostListItem) IsSet() bool {
	return v.isSet
}

func (v *NullableHostListItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostListItem(val *HostListItem) *NullableHostListItem {
	return &NullableHostListItem{value: val, isSet: true}
}

func (v NullableHostListItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostListItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


