/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Host type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Host{}

// Host struct for Host
type Host struct {
	// Unique Identifier for VMs, Hosts, Cluster, RFC 4122
	Uuid *string `json:"uuid,omitempty"`
	Hostdef *Hostdef `json:"hostdef,omitempty"`
	Hoststate *Hoststate `json:"hoststate,omitempty"`
	Hostresources *Hostresources `json:"hostresources,omitempty"`
}

// NewHost instantiates a new Host object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHost() *Host {
	this := Host{}
	return &this
}

// NewHostWithDefaults instantiates a new Host object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostWithDefaults() *Host {
	this := Host{}
	return &this
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *Host) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *Host) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *Host) SetUuid(v string) {
	o.Uuid = &v
}

// GetHostdef returns the Hostdef field value if set, zero value otherwise.
func (o *Host) GetHostdef() Hostdef {
	if o == nil || IsNil(o.Hostdef) {
		var ret Hostdef
		return ret
	}
	return *o.Hostdef
}

// GetHostdefOk returns a tuple with the Hostdef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetHostdefOk() (*Hostdef, bool) {
	if o == nil || IsNil(o.Hostdef) {
		return nil, false
	}
	return o.Hostdef, true
}

// HasHostdef returns a boolean if a field has been set.
func (o *Host) HasHostdef() bool {
	if o != nil && !IsNil(o.Hostdef) {
		return true
	}

	return false
}

// SetHostdef gets a reference to the given Hostdef and assigns it to the Hostdef field.
func (o *Host) SetHostdef(v Hostdef) {
	o.Hostdef = &v
}

// GetHoststate returns the Hoststate field value if set, zero value otherwise.
func (o *Host) GetHoststate() Hoststate {
	if o == nil || IsNil(o.Hoststate) {
		var ret Hoststate
		return ret
	}
	return *o.Hoststate
}

// GetHoststateOk returns a tuple with the Hoststate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetHoststateOk() (*Hoststate, bool) {
	if o == nil || IsNil(o.Hoststate) {
		return nil, false
	}
	return o.Hoststate, true
}

// HasHoststate returns a boolean if a field has been set.
func (o *Host) HasHoststate() bool {
	if o != nil && !IsNil(o.Hoststate) {
		return true
	}

	return false
}

// SetHoststate gets a reference to the given Hoststate and assigns it to the Hoststate field.
func (o *Host) SetHoststate(v Hoststate) {
	o.Hoststate = &v
}

// GetHostresources returns the Hostresources field value if set, zero value otherwise.
func (o *Host) GetHostresources() Hostresources {
	if o == nil || IsNil(o.Hostresources) {
		var ret Hostresources
		return ret
	}
	return *o.Hostresources
}

// GetHostresourcesOk returns a tuple with the Hostresources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Host) GetHostresourcesOk() (*Hostresources, bool) {
	if o == nil || IsNil(o.Hostresources) {
		return nil, false
	}
	return o.Hostresources, true
}

// HasHostresources returns a boolean if a field has been set.
func (o *Host) HasHostresources() bool {
	if o != nil && !IsNil(o.Hostresources) {
		return true
	}

	return false
}

// SetHostresources gets a reference to the given Hostresources and assigns it to the Hostresources field.
func (o *Host) SetHostresources(v Hostresources) {
	o.Hostresources = &v
}

func (o Host) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Host) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Hostdef) {
		toSerialize["hostdef"] = o.Hostdef
	}
	if !IsNil(o.Hoststate) {
		toSerialize["hoststate"] = o.Hoststate
	}
	if !IsNil(o.Hostresources) {
		toSerialize["hostresources"] = o.Hostresources
	}
	return toSerialize, nil
}

type NullableHost struct {
	value *Host
	isSet bool
}

func (v NullableHost) Get() *Host {
	return v.value
}

func (v *NullableHost) Set(val *Host) {
	v.value = val
	v.isSet = true
}

func (v NullableHost) IsSet() bool {
	return v.isSet
}

func (v *NullableHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHost(val *Host) *NullableHost {
	return &NullableHost{value: val, isSet: true}
}

func (v NullableHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


