/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DiskProvMode disk provisioning mode: thick or thin virtual disks (not relevant for iSCSI LUNs, use NONE) 
type DiskProvMode int16

// List of disk_prov_mode
const (
	DISK_PROV_NONE DiskProvMode = 0
	DISK_PROV_THIN DiskProvMode = 1
	DISK_PROV_THICK DiskProvMode = 2
)

// All allowed values of DiskProvMode enum
var AllowedDiskProvModeEnumValues = []DiskProvMode{
	0,
	1,
	2,
}

func (v *DiskProvMode) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiskProvMode(value)
	for _, existing := range AllowedDiskProvModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiskProvMode", value)
}

// NewDiskProvModeFromValue returns a pointer to a valid DiskProvMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiskProvModeFromValue(v int16) (*DiskProvMode, error) {
	ev := DiskProvMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiskProvMode: valid values are %v", v, AllowedDiskProvModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiskProvMode) IsValid() bool {
	for _, existing := range AllowedDiskProvModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to disk_prov_mode value
func (v DiskProvMode) Ptr() *DiskProvMode {
	return &v
}

type NullableDiskProvMode struct {
	value *DiskProvMode
	isSet bool
}

func (v NullableDiskProvMode) Get() *DiskProvMode {
	return v.value
}

func (v *NullableDiskProvMode) Set(val *DiskProvMode) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskProvMode) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskProvMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskProvMode(val *DiskProvMode) *NullableDiskProvMode {
	return &NullableDiskProvMode{value: val, isSet: true}
}

func (v NullableDiskProvMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskProvMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

