/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmListOptions{}

// VmListOptions struct for VmListOptions
type VmListOptions struct {
	Filter VmListFields `json:"filter"`
	Page Page `json:"page"`
}

type _VmListOptions VmListOptions

// NewVmListOptions instantiates a new VmListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmListOptions(filter VmListFields, page Page) *VmListOptions {
	this := VmListOptions{}
	this.Filter = filter
	this.Page = page
	return &this
}

// NewVmListOptionsWithDefaults instantiates a new VmListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListOptionsWithDefaults() *VmListOptions {
	this := VmListOptions{}
	return &this
}

// GetFilter returns the Filter field value
func (o *VmListOptions) GetFilter() VmListFields {
	if o == nil {
		var ret VmListFields
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *VmListOptions) GetFilterOk() (*VmListFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *VmListOptions) SetFilter(v VmListFields) {
	o.Filter = v
}

// GetPage returns the Page field value
func (o *VmListOptions) GetPage() Page {
	if o == nil {
		var ret Page
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *VmListOptions) GetPageOk() (*Page, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *VmListOptions) SetPage(v Page) {
	o.Page = v
}

func (o VmListOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter"] = o.Filter
	toSerialize["page"] = o.Page
	return toSerialize, nil
}

func (o *VmListOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter",
		"page",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmListOptions := _VmListOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmListOptions)

	if err != nil {
		return err
	}

	*o = VmListOptions(varVmListOptions)

	return err
}

type NullableVmListOptions struct {
	value *VmListOptions
	isSet bool
}

func (v NullableVmListOptions) Get() *VmListOptions {
	return v.value
}

func (v *NullableVmListOptions) Set(val *VmListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmListOptions(val *VmListOptions) *NullableVmListOptions {
	return &NullableVmListOptions{value: val, isSet: true}
}

func (v NullableVmListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


