/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DiskDevice the model 'DiskDevice'
type DiskDevice int16

// List of disk_device
const (
	DEVICE_DISK DiskDevice = 0
	DEVICE_CDROM DiskDevice = 1
)

// All allowed values of DiskDevice enum
var AllowedDiskDeviceEnumValues = []DiskDevice{
	0,
	1,
}

func (v *DiskDevice) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiskDevice(value)
	for _, existing := range AllowedDiskDeviceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiskDevice", value)
}

// NewDiskDeviceFromValue returns a pointer to a valid DiskDevice
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiskDeviceFromValue(v int16) (*DiskDevice, error) {
	ev := DiskDevice(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiskDevice: valid values are %v", v, AllowedDiskDeviceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiskDevice) IsValid() bool {
	for _, existing := range AllowedDiskDeviceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to disk_device value
func (v DiskDevice) Ptr() *DiskDevice {
	return &v
}

type NullableDiskDevice struct {
	value *DiskDevice
	isSet bool
}

func (v NullableDiskDevice) Get() *DiskDevice {
	return v.value
}

func (v *NullableDiskDevice) Set(val *DiskDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskDevice(val *DiskDevice) *NullableDiskDevice {
	return &NullableDiskDevice{value: val, isSet: true}
}

func (v NullableDiskDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

