/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Cpuarch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cpuarch{}

// Cpuarch struct for Cpuarch
type Cpuarch struct {
	// the CPU base architecture. Examples: \"x86_64\", \"aarch64\" 
	Arch string `json:"arch"`
	// vendor as per libvirt definition, x86_vendors.xml, arm_vendors.xml. Examples \"Intel\", \"AMD\" 
	Vendor string `json:"vendor"`
}

type _Cpuarch Cpuarch

// NewCpuarch instantiates a new Cpuarch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpuarch(arch string, vendor string) *Cpuarch {
	this := Cpuarch{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Arch = arch
	this.Vendor = vendor
	return &this
}

// NewCpuarchWithDefaults instantiates a new Cpuarch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpuarchWithDefaults() *Cpuarch {
	this := Cpuarch{}
	return &this
}

// GetArch returns the Arch field value
func (o *Cpuarch) GetArch() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Arch
}

// GetArchOk returns a tuple with the Arch field value
// and a boolean to check if the value has been set.
func (o *Cpuarch) GetArchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Arch, true
}

// SetArch sets field value
func (o *Cpuarch) SetArch(v string) {
	o.Arch = v
}

// GetVendor returns the Vendor field value
func (o *Cpuarch) GetVendor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value
// and a boolean to check if the value has been set.
func (o *Cpuarch) GetVendorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vendor, true
}

// SetVendor sets field value
func (o *Cpuarch) SetVendor(v string) {
	o.Vendor = v
}

func (o Cpuarch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["arch"] = o.Arch
	toSerialize["vendor"] = o.Vendor
	return toSerialize, nil
}

type NullableCpuarch struct {
	value *Cpuarch
	isSet bool
}

func (v NullableCpuarch) Get() *Cpuarch {
	return v.value
}

func (v *NullableCpuarch) Set(val *Cpuarch) {
	v.value = val
	v.isSet = true
}

func (v NullableCpuarch) IsSet() bool {
	return v.isSet
}

func (v *NullableCpuarch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpuarch(val *Cpuarch) *NullableCpuarch {
	return &NullableCpuarch{value: val, isSet: true}
}

func (v NullableCpuarch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpuarch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


