/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmListFields type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmListFields{}

// VmListFields struct for VmListFields
type VmListFields struct {
	Name *string `json:"name,omitempty"`
	// Unique Identifier for VMs, Hosts, Cluster, RFC 4122
	Host *string `json:"host,omitempty"`
	Vmrunstate *Vmrunstate `json:"vmrunstate,omitempty"`
	// vlanid for all traffic from/to this VM. 0 = automatically assign
	Vlanid *int32 `json:"vlanid,omitempty"`
	// Custom Fields
	Custom []CustomField `json:"custom,omitempty"`
}

// NewVmListFields instantiates a new VmListFields object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmListFields() *VmListFields {
	this := VmListFields{}
	return &this
}

// NewVmListFieldsWithDefaults instantiates a new VmListFields object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListFieldsWithDefaults() *VmListFields {
	this := VmListFields{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VmListFields) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListFields) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VmListFields) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VmListFields) SetName(v string) {
	o.Name = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *VmListFields) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListFields) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *VmListFields) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *VmListFields) SetHost(v string) {
	o.Host = &v
}

// GetVmrunstate returns the Vmrunstate field value if set, zero value otherwise.
func (o *VmListFields) GetVmrunstate() Vmrunstate {
	if o == nil || IsNil(o.Vmrunstate) {
		var ret Vmrunstate
		return ret
	}
	return *o.Vmrunstate
}

// GetVmrunstateOk returns a tuple with the Vmrunstate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListFields) GetVmrunstateOk() (*Vmrunstate, bool) {
	if o == nil || IsNil(o.Vmrunstate) {
		return nil, false
	}
	return o.Vmrunstate, true
}

// HasVmrunstate returns a boolean if a field has been set.
func (o *VmListFields) HasVmrunstate() bool {
	if o != nil && !IsNil(o.Vmrunstate) {
		return true
	}

	return false
}

// SetVmrunstate gets a reference to the given Vmrunstate and assigns it to the Vmrunstate field.
func (o *VmListFields) SetVmrunstate(v Vmrunstate) {
	o.Vmrunstate = &v
}

// GetVlanid returns the Vlanid field value if set, zero value otherwise.
func (o *VmListFields) GetVlanid() int32 {
	if o == nil || IsNil(o.Vlanid) {
		var ret int32
		return ret
	}
	return *o.Vlanid
}

// GetVlanidOk returns a tuple with the Vlanid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListFields) GetVlanidOk() (*int32, bool) {
	if o == nil || IsNil(o.Vlanid) {
		return nil, false
	}
	return o.Vlanid, true
}

// HasVlanid returns a boolean if a field has been set.
func (o *VmListFields) HasVlanid() bool {
	if o != nil && !IsNil(o.Vlanid) {
		return true
	}

	return false
}

// SetVlanid gets a reference to the given int32 and assigns it to the Vlanid field.
func (o *VmListFields) SetVlanid(v int32) {
	o.Vlanid = &v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *VmListFields) GetCustom() []CustomField {
	if o == nil || IsNil(o.Custom) {
		var ret []CustomField
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmListFields) GetCustomOk() ([]CustomField, bool) {
	if o == nil || IsNil(o.Custom) {
		return nil, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *VmListFields) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given []CustomField and assigns it to the Custom field.
func (o *VmListFields) SetCustom(v []CustomField) {
	o.Custom = v
}

func (o VmListFields) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmListFields) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Vmrunstate) {
		toSerialize["vmrunstate"] = o.Vmrunstate
	}
	if !IsNil(o.Vlanid) {
		toSerialize["vlanid"] = o.Vlanid
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	return toSerialize, nil
}

type NullableVmListFields struct {
	value *VmListFields
	isSet bool
}

func (v NullableVmListFields) Get() *VmListFields {
	return v.value
}

func (v *NullableVmListFields) Set(val *VmListFields) {
	v.value = val
	v.isSet = true
}

func (v NullableVmListFields) IsSet() bool {
	return v.isSet
}

func (v *NullableVmListFields) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmListFields(val *VmListFields) *NullableVmListFields {
	return &NullableVmListFields{value: val, isSet: true}
}

func (v NullableVmListFields) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmListFields) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


