/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VmMigrateInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmMigrateInfo{}

// VmMigrateInfo struct for VmMigrateInfo
type VmMigrateInfo struct {
	// the status of the migration
	State *string `json:"state,omitempty"`
	Progress *VmMigrateInfoProgress `json:"progress,omitempty"`
}

// NewVmMigrateInfo instantiates a new VmMigrateInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmMigrateInfo() *VmMigrateInfo {
	this := VmMigrateInfo{}
	return &this
}

// NewVmMigrateInfoWithDefaults instantiates a new VmMigrateInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmMigrateInfoWithDefaults() *VmMigrateInfo {
	this := VmMigrateInfo{}
	return &this
}

// GetState returns the State field value if set, zero value otherwise.
func (o *VmMigrateInfo) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateInfo) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *VmMigrateInfo) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *VmMigrateInfo) SetState(v string) {
	o.State = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *VmMigrateInfo) GetProgress() VmMigrateInfoProgress {
	if o == nil || IsNil(o.Progress) {
		var ret VmMigrateInfoProgress
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VmMigrateInfo) GetProgressOk() (*VmMigrateInfoProgress, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *VmMigrateInfo) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given VmMigrateInfoProgress and assigns it to the Progress field.
func (o *VmMigrateInfo) SetProgress(v VmMigrateInfoProgress) {
	o.Progress = &v
}

func (o VmMigrateInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VmMigrateInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	return toSerialize, nil
}

type NullableVmMigrateInfo struct {
	value *VmMigrateInfo
	isSet bool
}

func (v NullableVmMigrateInfo) Get() *VmMigrateInfo {
	return v.value
}

func (v *NullableVmMigrateInfo) Set(val *VmMigrateInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVmMigrateInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVmMigrateInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmMigrateInfo(val *VmMigrateInfo) *NullableVmMigrateInfo {
	return &NullableVmMigrateInfo{value: val, isSet: true}
}

func (v NullableVmMigrateInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmMigrateInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


