/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// LogClass category of a log code, derived as code / 1000 + 1
type LogClass int16

// List of log_class
const (
	LOG_CLASS_NONE LogClass = 0
	LOG_CLASS_OP LogClass = 1
	LOG_CLASS_ERROR LogClass = 2
	LOG_CLASS_GUEST LogClass = 3
)

// All allowed values of LogClass enum
var AllowedLogClassEnumValues = []LogClass{
	0,
	1,
	2,
	3,
}

func (v *LogClass) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := LogClass(value)
	for _, existing := range AllowedLogClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid LogClass", value)
}

// NewLogClassFromValue returns a pointer to a valid LogClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewLogClassFromValue(v int16) (*LogClass, error) {
	ev := LogClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for LogClass: valid values are %v", v, AllowedLogClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v LogClass) IsValid() bool {
	for _, existing := range AllowedLogClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to log_class value
func (v LogClass) Ptr() *LogClass {
	return &v
}

type NullableLogClass struct {
	value *LogClass
	isSet bool
}

func (v NullableLogClass) Get() *LogClass {
	return v.value
}

func (v *NullableLogClass) Set(val *LogClass) {
	v.value = val
	v.isSet = true
}

func (v NullableLogClass) IsSet() bool {
	return v.isSet
}

func (v *NullableLogClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogClass(val *LogClass) *NullableLogClass {
	return &NullableLogClass{value: val, isSet: true}
}

func (v NullableLogClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

