/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Hostresource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Hostresource{}

// Hostresource struct for Hostresource
type Hostresource struct {
	// total available on the host
	Total int32 `json:"total"`
	// amount currently in use
	Used int32 `json:"used"`
	// amount currently free (does not take into account reservations)
	Free int32 `json:"free"`
	// amount pre-reserved for the OS and the virtualization stack
	ReservedOs int32 `json:"reserved_os"`
	// amount pre-reserved for running the guests currently on this host
	ReservedVms int32 `json:"reserved_vms"`
	// amount used for running vm guests
	UsedVms int32 `json:"used_vms"`
	// amount available for other VMs (total - reserved_vms - reserved_os)
	AvailableVms int32 `json:"available_vms"`
}

type _Hostresource Hostresource

// NewHostresource instantiates a new Hostresource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostresource(total int32, used int32, free int32, reservedOs int32, reservedVms int32, usedVms int32, availableVms int32) *Hostresource {
	this := Hostresource{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Total = total
	this.Used = used
	this.Free = free
	this.ReservedOs = reservedOs
	this.ReservedVms = reservedVms
	this.UsedVms = usedVms
	this.AvailableVms = availableVms
	return &this
}

// NewHostresourceWithDefaults instantiates a new Hostresource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostresourceWithDefaults() *Hostresource {
	this := Hostresource{}
	return &this
}

// GetTotal returns the Total field value
func (o *Hostresource) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *Hostresource) SetTotal(v int32) {
	o.Total = v
}

// GetUsed returns the Used field value
func (o *Hostresource) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *Hostresource) SetUsed(v int32) {
	o.Used = v
}

// GetFree returns the Free field value
func (o *Hostresource) GetFree() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Free
}

// GetFreeOk returns a tuple with the Free field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetFreeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Free, true
}

// SetFree sets field value
func (o *Hostresource) SetFree(v int32) {
	o.Free = v
}

// GetReservedOs returns the ReservedOs field value
func (o *Hostresource) GetReservedOs() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedOs
}

// GetReservedOsOk returns a tuple with the ReservedOs field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetReservedOsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedOs, true
}

// SetReservedOs sets field value
func (o *Hostresource) SetReservedOs(v int32) {
	o.ReservedOs = v
}

// GetReservedVms returns the ReservedVms field value
func (o *Hostresource) GetReservedVms() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReservedVms
}

// GetReservedVmsOk returns a tuple with the ReservedVms field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetReservedVmsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReservedVms, true
}

// SetReservedVms sets field value
func (o *Hostresource) SetReservedVms(v int32) {
	o.ReservedVms = v
}

// GetUsedVms returns the UsedVms field value
func (o *Hostresource) GetUsedVms() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UsedVms
}

// GetUsedVmsOk returns a tuple with the UsedVms field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetUsedVmsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsedVms, true
}

// SetUsedVms sets field value
func (o *Hostresource) SetUsedVms(v int32) {
	o.UsedVms = v
}

// GetAvailableVms returns the AvailableVms field value
func (o *Hostresource) GetAvailableVms() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AvailableVms
}

// GetAvailableVmsOk returns a tuple with the AvailableVms field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetAvailableVmsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AvailableVms, true
}

// SetAvailableVms sets field value
func (o *Hostresource) SetAvailableVms(v int32) {
	o.AvailableVms = v
}

func (o Hostresource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["used"] = o.Used
	toSerialize["free"] = o.Free
	toSerialize["reserved_os"] = o.ReservedOs
	toSerialize["reserved_vms"] = o.ReservedVms
	toSerialize["used_vms"] = o.UsedVms
	toSerialize["available_vms"] = o.AvailableVms
	return toSerialize, nil
}

type NullableHostresource struct {
	value *Hostresource
	isSet bool
}

func (v NullableHostresource) Get() *Hostresource {
	return v.value
}

func (v *NullableHostresource) Set(val *Hostresource) {
	v.value = val
	v.isSet = true
}

func (v NullableHostresource) IsSet() bool {
	return v.isSet
}

func (v *NullableHostresource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostresource(val *Hostresource) *NullableHostresource {
	return &NullableHostresource{value: val, isSet: true}
}

func (v NullableHostresource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostresource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


