/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Host type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Host{}

// Host struct for Host
type Host struct {
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Uuid string `json:"uuid"`
	Def Hostdef `json:"def"`
	State Hoststate `json:"state"`
	// computing resources of the host.
	Resources Hostresources `json:"resources"`
	// 64bit UTC Unix timestamp
	Ts int64 `json:"ts"`
}

type _Host Host

// NewHost instantiates a new Host object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHost(uuid string, def Hostdef, state Hoststate, resources Hostresources, ts int64) *Host {
	this := Host{}
	this.Uuid = uuid
	this.Def = def
	this.State = state
	this.Resources = resources
	this.Ts = ts
	return &this
}

// NewHostWithDefaults instantiates a new Host object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostWithDefaults() *Host {
	this := Host{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Host) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Host) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Host) SetUuid(v string) {
	o.Uuid = v
}

// GetDef returns the Def field value
func (o *Host) GetDef() Hostdef {
	if o == nil {
		var ret Hostdef
		return ret
	}

	return o.Def
}

// GetDefOk returns a tuple with the Def field value
// and a boolean to check if the value has been set.
func (o *Host) GetDefOk() (*Hostdef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Def, true
}

// SetDef sets field value
func (o *Host) SetDef(v Hostdef) {
	o.Def = v
}

// GetState returns the State field value
func (o *Host) GetState() Hoststate {
	if o == nil {
		var ret Hoststate
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Host) GetStateOk() (*Hoststate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Host) SetState(v Hoststate) {
	o.State = v
}

// GetResources returns the Resources field value
func (o *Host) GetResources() Hostresources {
	if o == nil {
		var ret Hostresources
		return ret
	}

	return o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value
// and a boolean to check if the value has been set.
func (o *Host) GetResourcesOk() (*Hostresources, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resources, true
}

// SetResources sets field value
func (o *Host) SetResources(v Hostresources) {
	o.Resources = v
}

// GetTs returns the Ts field value
func (o *Host) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *Host) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *Host) SetTs(v int64) {
	o.Ts = v
}

func (o Host) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Host) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["def"] = o.Def
	toSerialize["state"] = o.State
	toSerialize["resources"] = o.Resources
	toSerialize["ts"] = o.Ts
	return toSerialize, nil
}

func (o *Host) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"def",
		"state",
		"resources",
		"ts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHost := _Host{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHost)

	if err != nil {
		return err
	}

	*o = Host(varHost)

	return err
}

type NullableHost struct {
	value *Host
	isSet bool
}

func (v NullableHost) Get() *Host {
	return v.value
}

func (v *NullableHost) Set(val *Host) {
	v.value = val
	v.isSet = true
}

func (v NullableHost) IsSet() bool {
	return v.isSet
}

func (v *NullableHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHost(val *Host) *NullableHost {
	return &NullableHost{value: val, isSet: true}
}

func (v NullableHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


