/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostdefSysinfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostdefSysinfo{}

// HostdefSysinfo struct for HostdefSysinfo
type HostdefSysinfo struct {
	// free-form string that may contain Core and OEM version information
	Version string `json:"version"`
	// mm/dd/yyyy format is required for SMBIOS version 2.3 and later
	Date string `json:"date"`
}

type _HostdefSysinfo HostdefSysinfo

// NewHostdefSysinfo instantiates a new HostdefSysinfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostdefSysinfo(version string, date string) *HostdefSysinfo {
	this := HostdefSysinfo{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Version = version
	this.Date = date
	return &this
}

// NewHostdefSysinfoWithDefaults instantiates a new HostdefSysinfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostdefSysinfoWithDefaults() *HostdefSysinfo {
	this := HostdefSysinfo{}
	return &this
}

// GetVersion returns the Version field value
func (o *HostdefSysinfo) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HostdefSysinfo) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HostdefSysinfo) SetVersion(v string) {
	o.Version = v
}

// GetDate returns the Date field value
func (o *HostdefSysinfo) GetDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *HostdefSysinfo) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *HostdefSysinfo) SetDate(v string) {
	o.Date = v
}

func (o HostdefSysinfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["date"] = o.Date
	return toSerialize, nil
}

type NullableHostdefSysinfo struct {
	value *HostdefSysinfo
	isSet bool
}

func (v NullableHostdefSysinfo) Get() *HostdefSysinfo {
	return v.value
}

func (v *NullableHostdefSysinfo) Set(val *HostdefSysinfo) {
	v.value = val
	v.isSet = true
}

func (v NullableHostdefSysinfo) IsSet() bool {
	return v.isSet
}

func (v *NullableHostdefSysinfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostdefSysinfo(val *HostdefSysinfo) *NullableHostdefSysinfo {
	return &NullableHostdefSysinfo{value: val, isSet: true}
}

func (v NullableHostdefSysinfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostdefSysinfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


