/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostListOptions{}

// HostListOptions struct for HostListOptions
type HostListOptions struct {
	Filter HostListFields `json:"filter"`
}

type _HostListOptions HostListOptions

// NewHostListOptions instantiates a new HostListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostListOptions(filter HostListFields) *HostListOptions {
	this := HostListOptions{}
	this.Filter = filter
	return &this
}

// NewHostListOptionsWithDefaults instantiates a new HostListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostListOptionsWithDefaults() *HostListOptions {
	this := HostListOptions{}
	return &this
}

// GetFilter returns the Filter field value
func (o *HostListOptions) GetFilter() HostListFields {
	if o == nil {
		var ret HostListFields
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *HostListOptions) GetFilterOk() (*HostListFields, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *HostListOptions) SetFilter(v HostListFields) {
	o.Filter = v
}

func (o HostListOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filter"] = o.Filter
	return toSerialize, nil
}

func (o *HostListOptions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"filter",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostListOptions := _HostListOptions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostListOptions)

	if err != nil {
		return err
	}

	*o = HostListOptions(varHostListOptions)

	return err
}

type NullableHostListOptions struct {
	value *HostListOptions
	isSet bool
}

func (v NullableHostListOptions) Get() *HostListOptions {
	return v.value
}

func (v *NullableHostListOptions) Set(val *HostListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableHostListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableHostListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostListOptions(val *HostListOptions) *NullableHostListOptions {
	return &NullableHostListOptions{value: val, isSet: true}
}

func (v NullableHostListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


