/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Hostresource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Hostresource{}

// Hostresource struct for Hostresource
type Hostresource struct {
	// total available on the host
	Total int32 `json:"total"`
	// amount currently in use
	Used int32 `json:"used"`
	// amount currently free (does not take into account reservations)
	Free int32 `json:"free"`
	// amount used by the OS and the host stack, excluding the amount used for VMs
	Usedos int32 `json:"usedos"`
	// amount pre-reserved for running the guests currently on this host
	Reservedvms int32 `json:"reservedvms"`
	// amount used for running vm guests
	Usedvms int32 `json:"usedvms"`
	// amount available for other VMs (total - reservedvms - usedos)
	Availablevms int32 `json:"availablevms"`
}

type _Hostresource Hostresource

// NewHostresource instantiates a new Hostresource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostresource(total int32, used int32, free int32, usedos int32, reservedvms int32, usedvms int32, availablevms int32) *Hostresource {
	this := Hostresource{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Total = total
	this.Used = used
	this.Free = free
	this.Usedos = usedos
	this.Reservedvms = reservedvms
	this.Usedvms = usedvms
	this.Availablevms = availablevms
	return &this
}

// NewHostresourceWithDefaults instantiates a new Hostresource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostresourceWithDefaults() *Hostresource {
	this := Hostresource{}
	return &this
}

// GetTotal returns the Total field value
func (o *Hostresource) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *Hostresource) SetTotal(v int32) {
	o.Total = v
}

// GetUsed returns the Used field value
func (o *Hostresource) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *Hostresource) SetUsed(v int32) {
	o.Used = v
}

// GetFree returns the Free field value
func (o *Hostresource) GetFree() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Free
}

// GetFreeOk returns a tuple with the Free field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetFreeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Free, true
}

// SetFree sets field value
func (o *Hostresource) SetFree(v int32) {
	o.Free = v
}

// GetUsedos returns the Usedos field value
func (o *Hostresource) GetUsedos() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Usedos
}

// GetUsedosOk returns a tuple with the Usedos field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetUsedosOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usedos, true
}

// SetUsedos sets field value
func (o *Hostresource) SetUsedos(v int32) {
	o.Usedos = v
}

// GetReservedvms returns the Reservedvms field value
func (o *Hostresource) GetReservedvms() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Reservedvms
}

// GetReservedvmsOk returns a tuple with the Reservedvms field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetReservedvmsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reservedvms, true
}

// SetReservedvms sets field value
func (o *Hostresource) SetReservedvms(v int32) {
	o.Reservedvms = v
}

// GetUsedvms returns the Usedvms field value
func (o *Hostresource) GetUsedvms() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Usedvms
}

// GetUsedvmsOk returns a tuple with the Usedvms field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetUsedvmsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usedvms, true
}

// SetUsedvms sets field value
func (o *Hostresource) SetUsedvms(v int32) {
	o.Usedvms = v
}

// GetAvailablevms returns the Availablevms field value
func (o *Hostresource) GetAvailablevms() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Availablevms
}

// GetAvailablevmsOk returns a tuple with the Availablevms field value
// and a boolean to check if the value has been set.
func (o *Hostresource) GetAvailablevmsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Availablevms, true
}

// SetAvailablevms sets field value
func (o *Hostresource) SetAvailablevms(v int32) {
	o.Availablevms = v
}

func (o Hostresource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["total"] = o.Total
	toSerialize["used"] = o.Used
	toSerialize["free"] = o.Free
	toSerialize["usedos"] = o.Usedos
	toSerialize["reservedvms"] = o.Reservedvms
	toSerialize["usedvms"] = o.Usedvms
	toSerialize["availablevms"] = o.Availablevms
	return toSerialize, nil
}

type NullableHostresource struct {
	value *Hostresource
	isSet bool
}

func (v NullableHostresource) Get() *Hostresource {
	return v.value
}

func (v *NullableHostresource) Set(val *Hostresource) {
	v.value = val
	v.isSet = true
}

func (v NullableHostresource) IsSet() bool {
	return v.isSet
}

func (v *NullableHostresource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostresource(val *Hostresource) *NullableHostresource {
	return &NullableHostresource{value: val, isSet: true}
}

func (v NullableHostresource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostresource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


