/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DiskCreateMode whether to open an existing disk, or create a thin/thick disk
type DiskCreateMode int16

// List of disk_create_mode
const (
	DISK_NOCREATE DiskCreateMode = 0
	DISK_CREATE_THIN DiskCreateMode = 1
	DISK_CREATE_THICK DiskCreateMode = 2
)

// All allowed values of DiskCreateMode enum
var AllowedDiskCreateModeEnumValues = []DiskCreateMode{
	0,
	1,
	2,
}

func (v *DiskCreateMode) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiskCreateMode(value)
	for _, existing := range AllowedDiskCreateModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiskCreateMode", value)
}

// NewDiskCreateModeFromValue returns a pointer to a valid DiskCreateMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiskCreateModeFromValue(v int16) (*DiskCreateMode, error) {
	ev := DiskCreateMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiskCreateMode: valid values are %v", v, AllowedDiskCreateModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiskCreateMode) IsValid() bool {
	for _, existing := range AllowedDiskCreateModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to disk_create_mode value
func (v DiskCreateMode) Ptr() *DiskCreateMode {
	return &v
}

type NullableDiskCreateMode struct {
	value *DiskCreateMode
	isSet bool
}

func (v NullableDiskCreateMode) Get() *DiskCreateMode {
	return v.value
}

func (v *NullableDiskCreateMode) Set(val *DiskCreateMode) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskCreateMode) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskCreateMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskCreateMode(val *DiskCreateMode) *NullableDiskCreateMode {
	return &NullableDiskCreateMode{value: val, isSet: true}
}

func (v NullableDiskCreateMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskCreateMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

