/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CloudInitMethod the model 'CloudInitMethod'
type CloudInitMethod int16

// List of cloud_init_method
const (
	CI_METHOD_FWCFG CloudInitMethod = 0
	CI_METHOD_ISO CloudInitMethod = 1
)

// All allowed values of CloudInitMethod enum
var AllowedCloudInitMethodEnumValues = []CloudInitMethod{
	0,
	1,
}

func (v *CloudInitMethod) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CloudInitMethod(value)
	for _, existing := range AllowedCloudInitMethodEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CloudInitMethod", value)
}

// NewCloudInitMethodFromValue returns a pointer to a valid CloudInitMethod
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCloudInitMethodFromValue(v int16) (*CloudInitMethod, error) {
	ev := CloudInitMethod(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CloudInitMethod: valid values are %v", v, AllowedCloudInitMethodEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CloudInitMethod) IsValid() bool {
	for _, existing := range AllowedCloudInitMethodEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to cloud_init_method value
func (v CloudInitMethod) Ptr() *CloudInitMethod {
	return &v
}

type NullableCloudInitMethod struct {
	value *CloudInitMethod
	isSet bool
}

func (v NullableCloudInitMethod) Get() *CloudInitMethod {
	return v.value
}

func (v *NullableCloudInitMethod) Set(val *CloudInitMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableCloudInitMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableCloudInitMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCloudInitMethod(val *CloudInitMethod) *NullableCloudInitMethod {
	return &NullableCloudInitMethod{value: val, isSet: true}
}

func (v NullableCloudInitMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCloudInitMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

