/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Vmstats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vmstats{}

// Vmstats runtime stats of the VM
type Vmstats struct {
	// percent of cpus utilized for this VM. 100 = 1 cpu fully utilized
	CpuUtilization int32 `json:"cpu_utilization"`
	// (uint64) memory capacity in MiB (normal memory or hugepages)
	MemoryCapacity int64 `json:"memory_capacity"`
	// (uint64) QEMU RSS from VIR_DOMAIN_MEMORY_STAT_RSS
	MemoryUsed int64 `json:"memory_used"`
	// (uint64) virtual capacity from virDomainBlockInfo / MiB
	DiskCapacity int64 `json:"disk_capacity"`
	// (uint64) allocated from virDomainBlockInfo / MiB
	DiskAllocation int64 `json:"disk_allocation"`
	// (uint64) Physical from virDomainBlockInfo / MiB
	DiskPhysical int64 `json:"disk_physical"`
	// Net Rx KiB/s
	NetRxBw int32 `json:"net_rx_bw"`
	// Net Tx KiB/s
	NetTxBw int32 `json:"net_tx_bw"`
}

type _Vmstats Vmstats

// NewVmstats instantiates a new Vmstats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmstats(cpuUtilization int32, memoryCapacity int64, memoryUsed int64, diskCapacity int64, diskAllocation int64, diskPhysical int64, netRxBw int32, netTxBw int32) *Vmstats {
	this := Vmstats{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.CpuUtilization = cpuUtilization
	this.MemoryCapacity = memoryCapacity
	this.MemoryUsed = memoryUsed
	this.DiskCapacity = diskCapacity
	this.DiskAllocation = diskAllocation
	this.DiskPhysical = diskPhysical
	this.NetRxBw = netRxBw
	this.NetTxBw = netTxBw
	return &this
}

// NewVmstatsWithDefaults instantiates a new Vmstats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmstatsWithDefaults() *Vmstats {
	this := Vmstats{}
	return &this
}

// GetCpuUtilization returns the CpuUtilization field value
func (o *Vmstats) GetCpuUtilization() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CpuUtilization
}

// GetCpuUtilizationOk returns a tuple with the CpuUtilization field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetCpuUtilizationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuUtilization, true
}

// SetCpuUtilization sets field value
func (o *Vmstats) SetCpuUtilization(v int32) {
	o.CpuUtilization = v
}

// GetMemoryCapacity returns the MemoryCapacity field value
func (o *Vmstats) GetMemoryCapacity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MemoryCapacity
}

// GetMemoryCapacityOk returns a tuple with the MemoryCapacity field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetMemoryCapacityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryCapacity, true
}

// SetMemoryCapacity sets field value
func (o *Vmstats) SetMemoryCapacity(v int64) {
	o.MemoryCapacity = v
}

// GetMemoryUsed returns the MemoryUsed field value
func (o *Vmstats) GetMemoryUsed() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MemoryUsed
}

// GetMemoryUsedOk returns a tuple with the MemoryUsed field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetMemoryUsedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryUsed, true
}

// SetMemoryUsed sets field value
func (o *Vmstats) SetMemoryUsed(v int64) {
	o.MemoryUsed = v
}

// GetDiskCapacity returns the DiskCapacity field value
func (o *Vmstats) GetDiskCapacity() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskCapacity
}

// GetDiskCapacityOk returns a tuple with the DiskCapacity field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetDiskCapacityOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskCapacity, true
}

// SetDiskCapacity sets field value
func (o *Vmstats) SetDiskCapacity(v int64) {
	o.DiskCapacity = v
}

// GetDiskAllocation returns the DiskAllocation field value
func (o *Vmstats) GetDiskAllocation() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskAllocation
}

// GetDiskAllocationOk returns a tuple with the DiskAllocation field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetDiskAllocationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskAllocation, true
}

// SetDiskAllocation sets field value
func (o *Vmstats) SetDiskAllocation(v int64) {
	o.DiskAllocation = v
}

// GetDiskPhysical returns the DiskPhysical field value
func (o *Vmstats) GetDiskPhysical() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.DiskPhysical
}

// GetDiskPhysicalOk returns a tuple with the DiskPhysical field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetDiskPhysicalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiskPhysical, true
}

// SetDiskPhysical sets field value
func (o *Vmstats) SetDiskPhysical(v int64) {
	o.DiskPhysical = v
}

// GetNetRxBw returns the NetRxBw field value
func (o *Vmstats) GetNetRxBw() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetRxBw
}

// GetNetRxBwOk returns a tuple with the NetRxBw field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetNetRxBwOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetRxBw, true
}

// SetNetRxBw sets field value
func (o *Vmstats) SetNetRxBw(v int32) {
	o.NetRxBw = v
}

// GetNetTxBw returns the NetTxBw field value
func (o *Vmstats) GetNetTxBw() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetTxBw
}

// GetNetTxBwOk returns a tuple with the NetTxBw field value
// and a boolean to check if the value has been set.
func (o *Vmstats) GetNetTxBwOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetTxBw, true
}

// SetNetTxBw sets field value
func (o *Vmstats) SetNetTxBw(v int32) {
	o.NetTxBw = v
}

func (o Vmstats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu_utilization"] = o.CpuUtilization
	toSerialize["memory_capacity"] = o.MemoryCapacity
	toSerialize["memory_used"] = o.MemoryUsed
	toSerialize["disk_capacity"] = o.DiskCapacity
	toSerialize["disk_allocation"] = o.DiskAllocation
	toSerialize["disk_physical"] = o.DiskPhysical
	toSerialize["net_rx_bw"] = o.NetRxBw
	toSerialize["net_tx_bw"] = o.NetTxBw
	return toSerialize, nil
}

type NullableVmstats struct {
	value *Vmstats
	isSet bool
}

func (v NullableVmstats) Get() *Vmstats {
	return v.value
}

func (v *NullableVmstats) Set(val *Vmstats) {
	v.value = val
	v.isSet = true
}

func (v NullableVmstats) IsSet() bool {
	return v.isSet
}

func (v *NullableVmstats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmstats(val *Vmstats) *NullableVmstats {
	return &NullableVmstats{value: val, isSet: true}
}

func (v NullableVmstats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmstats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


