/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmList{}

// VmList struct for VmList
type VmList struct {
	Items []VmListItem `json:"items"`
}

type _VmList VmList

// NewVmList instantiates a new VmList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmList(items []VmListItem) *VmList {
	this := VmList{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Items = items
	return &this
}

// NewVmListWithDefaults instantiates a new VmList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmListWithDefaults() *VmList {
	this := VmList{}
	return &this
}

// GetItems returns the Items field value
func (o *VmList) GetItems() []VmListItem {
	if o == nil {
		var ret []VmListItem
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *VmList) GetItemsOk() ([]VmListItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *VmList) SetItems(v []VmListItem) {
	o.Items = v
}

func (o VmList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

type NullableVmList struct {
	value *VmList
	isSet bool
}

func (v NullableVmList) Get() *VmList {
	return v.value
}

func (v *NullableVmList) Set(val *VmList) {
	v.value = val
	v.isSet = true
}

func (v NullableVmList) IsSet() bool {
	return v.isSet
}

func (v *NullableVmList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmList(val *VmList) *NullableVmList {
	return &NullableVmList{value: val, isSet: true}
}

func (v NullableVmList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


