/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Vmdef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vmdef{}

// Vmdef struct for Vmdef
type Vmdef struct {
	Name string `json:"name"`
	Displayname *string `json:"displayname,omitempty"`
	// vlanid for all traffic from/to this VM. 0 = automatically assign
	Vlanid *int32 `json:"vlanid,omitempty"`
	WatchdogAction *string `json:"watchdog_action,omitempty"`
	Firmware *string `json:"firmware,omitempty"`
	// VM generation ID. Use special value \"auto\" to autogenerate
	Genid *string `json:"genid,omitempty"`
	// where the Virtual SMBIOS should get information from
	Smbios *string `json:"smbios,omitempty"`
	// enable SAP-specific VM advanced configuration
	Sap *bool `json:"sap,omitempty"`
	// Custom Fields
	Custom []CustomField `json:"custom,omitempty"`
	// disks attached to the VM
	Disks []Disk `json:"disks,omitempty"`
	// networks and bridges attached to the VM
	Nets []Net `json:"nets,omitempty"`
	Cpudef *Cpudef `json:"cpudef,omitempty"`
	Memory *VmdefMemory `json:"memory,omitempty"`
}

type _Vmdef Vmdef

// NewVmdef instantiates a new Vmdef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmdef(name string) *Vmdef {
	this := Vmdef{}
	this.Name = name
	return &this
}

// NewVmdefWithDefaults instantiates a new Vmdef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmdefWithDefaults() *Vmdef {
	this := Vmdef{}
	return &this
}

// GetName returns the Name field value
func (o *Vmdef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Vmdef) SetName(v string) {
	o.Name = v
}

// GetDisplayname returns the Displayname field value if set, zero value otherwise.
func (o *Vmdef) GetDisplayname() string {
	if o == nil || IsNil(o.Displayname) {
		var ret string
		return ret
	}
	return *o.Displayname
}

// GetDisplaynameOk returns a tuple with the Displayname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetDisplaynameOk() (*string, bool) {
	if o == nil || IsNil(o.Displayname) {
		return nil, false
	}
	return o.Displayname, true
}

// HasDisplayname returns a boolean if a field has been set.
func (o *Vmdef) HasDisplayname() bool {
	if o != nil && !IsNil(o.Displayname) {
		return true
	}

	return false
}

// SetDisplayname gets a reference to the given string and assigns it to the Displayname field.
func (o *Vmdef) SetDisplayname(v string) {
	o.Displayname = &v
}

// GetVlanid returns the Vlanid field value if set, zero value otherwise.
func (o *Vmdef) GetVlanid() int32 {
	if o == nil || IsNil(o.Vlanid) {
		var ret int32
		return ret
	}
	return *o.Vlanid
}

// GetVlanidOk returns a tuple with the Vlanid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetVlanidOk() (*int32, bool) {
	if o == nil || IsNil(o.Vlanid) {
		return nil, false
	}
	return o.Vlanid, true
}

// HasVlanid returns a boolean if a field has been set.
func (o *Vmdef) HasVlanid() bool {
	if o != nil && !IsNil(o.Vlanid) {
		return true
	}

	return false
}

// SetVlanid gets a reference to the given int32 and assigns it to the Vlanid field.
func (o *Vmdef) SetVlanid(v int32) {
	o.Vlanid = &v
}

// GetWatchdogAction returns the WatchdogAction field value if set, zero value otherwise.
func (o *Vmdef) GetWatchdogAction() string {
	if o == nil || IsNil(o.WatchdogAction) {
		var ret string
		return ret
	}
	return *o.WatchdogAction
}

// GetWatchdogActionOk returns a tuple with the WatchdogAction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetWatchdogActionOk() (*string, bool) {
	if o == nil || IsNil(o.WatchdogAction) {
		return nil, false
	}
	return o.WatchdogAction, true
}

// HasWatchdogAction returns a boolean if a field has been set.
func (o *Vmdef) HasWatchdogAction() bool {
	if o != nil && !IsNil(o.WatchdogAction) {
		return true
	}

	return false
}

// SetWatchdogAction gets a reference to the given string and assigns it to the WatchdogAction field.
func (o *Vmdef) SetWatchdogAction(v string) {
	o.WatchdogAction = &v
}

// GetFirmware returns the Firmware field value if set, zero value otherwise.
func (o *Vmdef) GetFirmware() string {
	if o == nil || IsNil(o.Firmware) {
		var ret string
		return ret
	}
	return *o.Firmware
}

// GetFirmwareOk returns a tuple with the Firmware field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetFirmwareOk() (*string, bool) {
	if o == nil || IsNil(o.Firmware) {
		return nil, false
	}
	return o.Firmware, true
}

// HasFirmware returns a boolean if a field has been set.
func (o *Vmdef) HasFirmware() bool {
	if o != nil && !IsNil(o.Firmware) {
		return true
	}

	return false
}

// SetFirmware gets a reference to the given string and assigns it to the Firmware field.
func (o *Vmdef) SetFirmware(v string) {
	o.Firmware = &v
}

// GetGenid returns the Genid field value if set, zero value otherwise.
func (o *Vmdef) GetGenid() string {
	if o == nil || IsNil(o.Genid) {
		var ret string
		return ret
	}
	return *o.Genid
}

// GetGenidOk returns a tuple with the Genid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetGenidOk() (*string, bool) {
	if o == nil || IsNil(o.Genid) {
		return nil, false
	}
	return o.Genid, true
}

// HasGenid returns a boolean if a field has been set.
func (o *Vmdef) HasGenid() bool {
	if o != nil && !IsNil(o.Genid) {
		return true
	}

	return false
}

// SetGenid gets a reference to the given string and assigns it to the Genid field.
func (o *Vmdef) SetGenid(v string) {
	o.Genid = &v
}

// GetSmbios returns the Smbios field value if set, zero value otherwise.
func (o *Vmdef) GetSmbios() string {
	if o == nil || IsNil(o.Smbios) {
		var ret string
		return ret
	}
	return *o.Smbios
}

// GetSmbiosOk returns a tuple with the Smbios field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetSmbiosOk() (*string, bool) {
	if o == nil || IsNil(o.Smbios) {
		return nil, false
	}
	return o.Smbios, true
}

// HasSmbios returns a boolean if a field has been set.
func (o *Vmdef) HasSmbios() bool {
	if o != nil && !IsNil(o.Smbios) {
		return true
	}

	return false
}

// SetSmbios gets a reference to the given string and assigns it to the Smbios field.
func (o *Vmdef) SetSmbios(v string) {
	o.Smbios = &v
}

// GetSap returns the Sap field value if set, zero value otherwise.
func (o *Vmdef) GetSap() bool {
	if o == nil || IsNil(o.Sap) {
		var ret bool
		return ret
	}
	return *o.Sap
}

// GetSapOk returns a tuple with the Sap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetSapOk() (*bool, bool) {
	if o == nil || IsNil(o.Sap) {
		return nil, false
	}
	return o.Sap, true
}

// HasSap returns a boolean if a field has been set.
func (o *Vmdef) HasSap() bool {
	if o != nil && !IsNil(o.Sap) {
		return true
	}

	return false
}

// SetSap gets a reference to the given bool and assigns it to the Sap field.
func (o *Vmdef) SetSap(v bool) {
	o.Sap = &v
}

// GetCustom returns the Custom field value if set, zero value otherwise.
func (o *Vmdef) GetCustom() []CustomField {
	if o == nil || IsNil(o.Custom) {
		var ret []CustomField
		return ret
	}
	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetCustomOk() ([]CustomField, bool) {
	if o == nil || IsNil(o.Custom) {
		return nil, false
	}
	return o.Custom, true
}

// HasCustom returns a boolean if a field has been set.
func (o *Vmdef) HasCustom() bool {
	if o != nil && !IsNil(o.Custom) {
		return true
	}

	return false
}

// SetCustom gets a reference to the given []CustomField and assigns it to the Custom field.
func (o *Vmdef) SetCustom(v []CustomField) {
	o.Custom = v
}

// GetDisks returns the Disks field value if set, zero value otherwise.
func (o *Vmdef) GetDisks() []Disk {
	if o == nil || IsNil(o.Disks) {
		var ret []Disk
		return ret
	}
	return o.Disks
}

// GetDisksOk returns a tuple with the Disks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetDisksOk() ([]Disk, bool) {
	if o == nil || IsNil(o.Disks) {
		return nil, false
	}
	return o.Disks, true
}

// HasDisks returns a boolean if a field has been set.
func (o *Vmdef) HasDisks() bool {
	if o != nil && !IsNil(o.Disks) {
		return true
	}

	return false
}

// SetDisks gets a reference to the given []Disk and assigns it to the Disks field.
func (o *Vmdef) SetDisks(v []Disk) {
	o.Disks = v
}

// GetNets returns the Nets field value if set, zero value otherwise.
func (o *Vmdef) GetNets() []Net {
	if o == nil || IsNil(o.Nets) {
		var ret []Net
		return ret
	}
	return o.Nets
}

// GetNetsOk returns a tuple with the Nets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetNetsOk() ([]Net, bool) {
	if o == nil || IsNil(o.Nets) {
		return nil, false
	}
	return o.Nets, true
}

// HasNets returns a boolean if a field has been set.
func (o *Vmdef) HasNets() bool {
	if o != nil && !IsNil(o.Nets) {
		return true
	}

	return false
}

// SetNets gets a reference to the given []Net and assigns it to the Nets field.
func (o *Vmdef) SetNets(v []Net) {
	o.Nets = v
}

// GetCpudef returns the Cpudef field value if set, zero value otherwise.
func (o *Vmdef) GetCpudef() Cpudef {
	if o == nil || IsNil(o.Cpudef) {
		var ret Cpudef
		return ret
	}
	return *o.Cpudef
}

// GetCpudefOk returns a tuple with the Cpudef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetCpudefOk() (*Cpudef, bool) {
	if o == nil || IsNil(o.Cpudef) {
		return nil, false
	}
	return o.Cpudef, true
}

// HasCpudef returns a boolean if a field has been set.
func (o *Vmdef) HasCpudef() bool {
	if o != nil && !IsNil(o.Cpudef) {
		return true
	}

	return false
}

// SetCpudef gets a reference to the given Cpudef and assigns it to the Cpudef field.
func (o *Vmdef) SetCpudef(v Cpudef) {
	o.Cpudef = &v
}

// GetMemory returns the Memory field value if set, zero value otherwise.
func (o *Vmdef) GetMemory() VmdefMemory {
	if o == nil || IsNil(o.Memory) {
		var ret VmdefMemory
		return ret
	}
	return *o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vmdef) GetMemoryOk() (*VmdefMemory, bool) {
	if o == nil || IsNil(o.Memory) {
		return nil, false
	}
	return o.Memory, true
}

// HasMemory returns a boolean if a field has been set.
func (o *Vmdef) HasMemory() bool {
	if o != nil && !IsNil(o.Memory) {
		return true
	}

	return false
}

// SetMemory gets a reference to the given VmdefMemory and assigns it to the Memory field.
func (o *Vmdef) SetMemory(v VmdefMemory) {
	o.Memory = &v
}

func (o Vmdef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vmdef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Displayname) {
		toSerialize["displayname"] = o.Displayname
	}
	if !IsNil(o.Vlanid) {
		toSerialize["vlanid"] = o.Vlanid
	}
	if !IsNil(o.WatchdogAction) {
		toSerialize["watchdog_action"] = o.WatchdogAction
	}
	if !IsNil(o.Firmware) {
		toSerialize["firmware"] = o.Firmware
	}
	if !IsNil(o.Genid) {
		toSerialize["genid"] = o.Genid
	}
	if !IsNil(o.Smbios) {
		toSerialize["smbios"] = o.Smbios
	}
	if !IsNil(o.Sap) {
		toSerialize["sap"] = o.Sap
	}
	if !IsNil(o.Custom) {
		toSerialize["custom"] = o.Custom
	}
	if !IsNil(o.Disks) {
		toSerialize["disks"] = o.Disks
	}
	if !IsNil(o.Nets) {
		toSerialize["nets"] = o.Nets
	}
	if !IsNil(o.Cpudef) {
		toSerialize["cpudef"] = o.Cpudef
	}
	if !IsNil(o.Memory) {
		toSerialize["memory"] = o.Memory
	}
	return toSerialize, nil
}

func (o *Vmdef) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVmdef := _Vmdef{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVmdef)

	if err != nil {
		return err
	}

	*o = Vmdef(varVmdef)

	return err
}

type NullableVmdef struct {
	value *Vmdef
	isSet bool
}

func (v NullableVmdef) Get() *Vmdef {
	return v.value
}

func (v *NullableVmdef) Set(val *Vmdef) {
	v.value = val
	v.isSet = true
}

func (v NullableVmdef) IsSet() bool {
	return v.isSet
}

func (v *NullableVmdef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmdef(val *Vmdef) *NullableVmdef {
	return &NullableVmdef{value: val, isSet: true}
}

func (v NullableVmdef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmdef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


