/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Vmdef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vmdef{}

// Vmdef struct for Vmdef
type Vmdef struct {
	Name string `json:"name"`
	Cpudef Cpudef `json:"cpudef"`
	Memory VmdefMemory `json:"memory"`
	Numa Numa `json:"numa"`
	// disks attached to the VM
	Disks []Disk `json:"disks"`
	// networks and bridges attached to the VM
	Nets []Net `json:"nets"`
	// vlanid for all traffic from/to this VM. 0 = no vlanid, -1 = automatically assign
	Vlanid int16 `json:"vlanid"`
	Firmware FirmwareType `json:"firmware"`
	// VM generation ID. Use special value \"auto\" to autogenerate
	Genid string `json:"genid"`
	// Custom Fields
	Custom []CustomField `json:"custom"`
}

type _Vmdef Vmdef

// NewVmdef instantiates a new Vmdef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmdef(name string, cpudef Cpudef, memory VmdefMemory, numa Numa, disks []Disk, nets []Net, vlanid int16, firmware FirmwareType, genid string, custom []CustomField) *Vmdef {
	this := Vmdef{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Name = name
	this.Cpudef = cpudef
	this.Memory = memory
	this.Numa = numa
	this.Disks = disks
	this.Nets = nets
	this.Vlanid = vlanid
	this.Firmware = firmware
	this.Genid = genid
	this.Custom = custom
	return &this
}

// NewVmdefWithDefaults instantiates a new Vmdef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmdefWithDefaults() *Vmdef {
	this := Vmdef{}
	return &this
}

// GetName returns the Name field value
func (o *Vmdef) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Vmdef) SetName(v string) {
	o.Name = v
}

// GetCpudef returns the Cpudef field value
func (o *Vmdef) GetCpudef() Cpudef {
	if o == nil {
		var ret Cpudef
		return ret
	}

	return o.Cpudef
}

// GetCpudefOk returns a tuple with the Cpudef field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetCpudefOk() (*Cpudef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpudef, true
}

// SetCpudef sets field value
func (o *Vmdef) SetCpudef(v Cpudef) {
	o.Cpudef = v
}

// GetMemory returns the Memory field value
func (o *Vmdef) GetMemory() VmdefMemory {
	if o == nil {
		var ret VmdefMemory
		return ret
	}

	return o.Memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetMemoryOk() (*VmdefMemory, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Memory, true
}

// SetMemory sets field value
func (o *Vmdef) SetMemory(v VmdefMemory) {
	o.Memory = v
}

// GetNuma returns the Numa field value
func (o *Vmdef) GetNuma() Numa {
	if o == nil {
		var ret Numa
		return ret
	}

	return o.Numa
}

// GetNumaOk returns a tuple with the Numa field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetNumaOk() (*Numa, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Numa, true
}

// SetNuma sets field value
func (o *Vmdef) SetNuma(v Numa) {
	o.Numa = v
}

// GetDisks returns the Disks field value
func (o *Vmdef) GetDisks() []Disk {
	if o == nil {
		var ret []Disk
		return ret
	}

	return o.Disks
}

// GetDisksOk returns a tuple with the Disks field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetDisksOk() ([]Disk, bool) {
	if o == nil {
		return nil, false
	}
	return o.Disks, true
}

// SetDisks sets field value
func (o *Vmdef) SetDisks(v []Disk) {
	o.Disks = v
}

// GetNets returns the Nets field value
func (o *Vmdef) GetNets() []Net {
	if o == nil {
		var ret []Net
		return ret
	}

	return o.Nets
}

// GetNetsOk returns a tuple with the Nets field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetNetsOk() ([]Net, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nets, true
}

// SetNets sets field value
func (o *Vmdef) SetNets(v []Net) {
	o.Nets = v
}

// GetVlanid returns the Vlanid field value
func (o *Vmdef) GetVlanid() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Vlanid
}

// GetVlanidOk returns a tuple with the Vlanid field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetVlanidOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vlanid, true
}

// SetVlanid sets field value
func (o *Vmdef) SetVlanid(v int16) {
	o.Vlanid = v
}

// GetFirmware returns the Firmware field value
func (o *Vmdef) GetFirmware() FirmwareType {
	if o == nil {
		var ret FirmwareType
		return ret
	}

	return o.Firmware
}

// GetFirmwareOk returns a tuple with the Firmware field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetFirmwareOk() (*FirmwareType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Firmware, true
}

// SetFirmware sets field value
func (o *Vmdef) SetFirmware(v FirmwareType) {
	o.Firmware = v
}

// GetGenid returns the Genid field value
func (o *Vmdef) GetGenid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Genid
}

// GetGenidOk returns a tuple with the Genid field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetGenidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Genid, true
}

// SetGenid sets field value
func (o *Vmdef) SetGenid(v string) {
	o.Genid = v
}

// GetCustom returns the Custom field value
func (o *Vmdef) GetCustom() []CustomField {
	if o == nil {
		var ret []CustomField
		return ret
	}

	return o.Custom
}

// GetCustomOk returns a tuple with the Custom field value
// and a boolean to check if the value has been set.
func (o *Vmdef) GetCustomOk() ([]CustomField, bool) {
	if o == nil {
		return nil, false
	}
	return o.Custom, true
}

// SetCustom sets field value
func (o *Vmdef) SetCustom(v []CustomField) {
	o.Custom = v
}

func (o Vmdef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["cpudef"] = o.Cpudef
	toSerialize["memory"] = o.Memory
	toSerialize["numa"] = o.Numa
	toSerialize["disks"] = o.Disks
	toSerialize["nets"] = o.Nets
	toSerialize["vlanid"] = o.Vlanid
	toSerialize["firmware"] = o.Firmware
	toSerialize["genid"] = o.Genid
	toSerialize["custom"] = o.Custom
	return toSerialize, nil
}

type NullableVmdef struct {
	value *Vmdef
	isSet bool
}

func (v NullableVmdef) Get() *Vmdef {
	return v.value
}

func (v *NullableVmdef) Set(val *Vmdef) {
	v.value = val
	v.isSet = true
}

func (v NullableVmdef) IsSet() bool {
	return v.isSet
}

func (v *NullableVmdef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmdef(val *Vmdef) *NullableVmdef {
	return &NullableVmdef{value: val, isSet: true}
}

func (v NullableVmdef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmdef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


