/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OplogItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OplogItem{}

// OplogItem struct for OplogItem
type OplogItem struct {
	// the operation code, see x-opcode. PERSISTED!
	Op int16 `json:"op"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Ts int64 `json:"ts"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	Te int64 `json:"te"`
	State OperationState `json:"state"`
	Msgs string `json:"msgs"`
	Msge string `json:"msge"`
}

type _OplogItem OplogItem

// NewOplogItem instantiates a new OplogItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOplogItem(op int16, ts int64, te int64, state OperationState, msgs string, msge string) *OplogItem {
	this := OplogItem{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Op = op
	this.Ts = ts
	this.Te = te
	this.State = state
	this.Msgs = msgs
	this.Msge = msge
	return &this
}

// NewOplogItemWithDefaults instantiates a new OplogItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOplogItemWithDefaults() *OplogItem {
	this := OplogItem{}
	return &this
}

// GetOp returns the Op field value
func (o *OplogItem) GetOp() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Op
}

// GetOpOk returns a tuple with the Op field value
// and a boolean to check if the value has been set.
func (o *OplogItem) GetOpOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Op, true
}

// SetOp sets field value
func (o *OplogItem) SetOp(v int16) {
	o.Op = v
}

// GetTs returns the Ts field value
func (o *OplogItem) GetTs() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Ts
}

// GetTsOk returns a tuple with the Ts field value
// and a boolean to check if the value has been set.
func (o *OplogItem) GetTsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ts, true
}

// SetTs sets field value
func (o *OplogItem) SetTs(v int64) {
	o.Ts = v
}

// GetTe returns the Te field value
func (o *OplogItem) GetTe() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Te
}

// GetTeOk returns a tuple with the Te field value
// and a boolean to check if the value has been set.
func (o *OplogItem) GetTeOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Te, true
}

// SetTe sets field value
func (o *OplogItem) SetTe(v int64) {
	o.Te = v
}

// GetState returns the State field value
func (o *OplogItem) GetState() OperationState {
	if o == nil {
		var ret OperationState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *OplogItem) GetStateOk() (*OperationState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *OplogItem) SetState(v OperationState) {
	o.State = v
}

// GetMsgs returns the Msgs field value
func (o *OplogItem) GetMsgs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msgs
}

// GetMsgsOk returns a tuple with the Msgs field value
// and a boolean to check if the value has been set.
func (o *OplogItem) GetMsgsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msgs, true
}

// SetMsgs sets field value
func (o *OplogItem) SetMsgs(v string) {
	o.Msgs = v
}

// GetMsge returns the Msge field value
func (o *OplogItem) GetMsge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msge
}

// GetMsgeOk returns a tuple with the Msge field value
// and a boolean to check if the value has been set.
func (o *OplogItem) GetMsgeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msge, true
}

// SetMsge sets field value
func (o *OplogItem) SetMsge(v string) {
	o.Msge = v
}

func (o OplogItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["op"] = o.Op
	toSerialize["ts"] = o.Ts
	toSerialize["te"] = o.Te
	toSerialize["state"] = o.State
	toSerialize["msgs"] = o.Msgs
	toSerialize["msge"] = o.Msge
	return toSerialize, nil
}

type NullableOplogItem struct {
	value *OplogItem
	isSet bool
}

func (v NullableOplogItem) Get() *OplogItem {
	return v.value
}

func (v *NullableOplogItem) Set(val *OplogItem) {
	v.value = val
	v.isSet = true
}

func (v NullableOplogItem) IsSet() bool {
	return v.isSet
}

func (v *NullableOplogItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOplogItem(val *OplogItem) *NullableOplogItem {
	return &NullableOplogItem{value: val, isSet: true}
}

func (v NullableOplogItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOplogItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


