/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Disk type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Disk{}

// Disk struct for Disk
type Disk struct {
	Path string `json:"path"`
	Device DiskDevice `json:"device"`
	Bus DiskBus `json:"bus"`
	CreateMode DiskCreateMode `json:"create_mode"`
	// size in MiB (use 0 for DISK_NOCREATE)
	Size int32 `json:"size"`
}

type _Disk Disk

// NewDisk instantiates a new Disk object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisk(path string, device DiskDevice, bus DiskBus, createMode DiskCreateMode, size int32) *Disk {
	this := Disk{}
	this.Path = path
	this.Device = device
	this.Bus = bus
	this.CreateMode = createMode
	this.Size = size
	return &this
}

// NewDiskWithDefaults instantiates a new Disk object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiskWithDefaults() *Disk {
	this := Disk{}
	return &this
}

// GetPath returns the Path field value
func (o *Disk) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *Disk) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *Disk) SetPath(v string) {
	o.Path = v
}

// GetDevice returns the Device field value
func (o *Disk) GetDevice() DiskDevice {
	if o == nil {
		var ret DiskDevice
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *Disk) GetDeviceOk() (*DiskDevice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *Disk) SetDevice(v DiskDevice) {
	o.Device = v
}

// GetBus returns the Bus field value
func (o *Disk) GetBus() DiskBus {
	if o == nil {
		var ret DiskBus
		return ret
	}

	return o.Bus
}

// GetBusOk returns a tuple with the Bus field value
// and a boolean to check if the value has been set.
func (o *Disk) GetBusOk() (*DiskBus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bus, true
}

// SetBus sets field value
func (o *Disk) SetBus(v DiskBus) {
	o.Bus = v
}

// GetCreateMode returns the CreateMode field value
func (o *Disk) GetCreateMode() DiskCreateMode {
	if o == nil {
		var ret DiskCreateMode
		return ret
	}

	return o.CreateMode
}

// GetCreateModeOk returns a tuple with the CreateMode field value
// and a boolean to check if the value has been set.
func (o *Disk) GetCreateModeOk() (*DiskCreateMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreateMode, true
}

// SetCreateMode sets field value
func (o *Disk) SetCreateMode(v DiskCreateMode) {
	o.CreateMode = v
}

// GetSize returns the Size field value
func (o *Disk) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *Disk) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *Disk) SetSize(v int32) {
	o.Size = v
}

func (o Disk) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Disk) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["device"] = o.Device
	toSerialize["bus"] = o.Bus
	toSerialize["create_mode"] = o.CreateMode
	toSerialize["size"] = o.Size
	return toSerialize, nil
}

func (o *Disk) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"device",
		"bus",
		"create_mode",
		"size",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisk := _Disk{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisk)

	if err != nil {
		return err
	}

	*o = Disk(varDisk)

	return err
}

type NullableDisk struct {
	value *Disk
	isSet bool
}

func (v NullableDisk) Get() *Disk {
	return v.value
}

func (v *NullableDisk) Set(val *Disk) {
	v.value = val
	v.isSet = true
}

func (v NullableDisk) IsSet() bool {
	return v.isSet
}

func (v *NullableDisk) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisk(val *Disk) *NullableDisk {
	return &NullableDisk{value: val, isSet: true}
}

func (v NullableDisk) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisk) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


