/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// NetModel the model 'NetModel'
type NetModel int16

// List of net_model
const (
	NET_MODEL_VIRTIO NetModel = 0
	NET_MODEL_E1000E NetModel = 1
	NET_MODEL_E1000 NetModel = 2
)

// All allowed values of NetModel enum
var AllowedNetModelEnumValues = []NetModel{
	0,
	1,
	2,
}

func (v *NetModel) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := NetModel(value)
	for _, existing := range AllowedNetModelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid NetModel", value)
}

// NewNetModelFromValue returns a pointer to a valid NetModel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewNetModelFromValue(v int16) (*NetModel, error) {
	ev := NetModel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for NetModel: valid values are %v", v, AllowedNetModelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v NetModel) IsValid() bool {
	for _, existing := range AllowedNetModelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to net_model value
func (v NetModel) Ptr() *NetModel {
	return &v
}

type NullableNetModel struct {
	value *NetModel
	isSet bool
}

func (v NullableNetModel) Get() *NetModel {
	return v.value
}

func (v *NullableNetModel) Set(val *NetModel) {
	v.value = val
	v.isSet = true
}

func (v NullableNetModel) IsSet() bool {
	return v.isSet
}

func (v *NullableNetModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetModel(val *NetModel) *NullableNetModel {
	return &NullableNetModel{value: val, isSet: true}
}

func (v NullableNetModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

