/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmLogListOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmLogListOptions{}

// VmLogListOptions struct for VmLogListOptions
type VmLogListOptions struct {
	// filter to a single log_class; 0 = all classes
	Class int16 `json:"class"`
	// filter to a single code, belonging to class if set; 0 = all codes, merged chronologically
	Code int16 `json:"code"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	From int64 `json:"from"`
	// 64bit UTC Unix timestamp in milliseconds since Epoc. A 0 value is used if the timestamp is not available.
	To int64 `json:"to"`
	// return only the last N records in range; 0 = no limit. Mutually exclusive with head.
	Tail int32 `json:"tail"`
	// return only the first N records in range; 0 = no limit. Mutually exclusive with tail.
	Head int32 `json:"head"`
	// false = chronological (oldest first); true = reverse chronological (newest first)
	Reverse bool `json:"reverse"`
}

type _VmLogListOptions VmLogListOptions

// NewVmLogListOptions instantiates a new VmLogListOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmLogListOptions(class int16, code int16, from int64, to int64, tail int32, head int32, reverse bool) *VmLogListOptions {
	this := VmLogListOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Class = class
	this.Code = code
	this.From = from
	this.To = to
	this.Tail = tail
	this.Head = head
	this.Reverse = reverse
	return &this
}

// NewVmLogListOptionsWithDefaults instantiates a new VmLogListOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmLogListOptionsWithDefaults() *VmLogListOptions {
	this := VmLogListOptions{}
	return &this
}

// GetClass returns the Class field value
func (o *VmLogListOptions) GetClass() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Class
}

// GetClassOk returns a tuple with the Class field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetClassOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Class, true
}

// SetClass sets field value
func (o *VmLogListOptions) SetClass(v int16) {
	o.Class = v
}

// GetCode returns the Code field value
func (o *VmLogListOptions) GetCode() int16 {
	if o == nil {
		var ret int16
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetCodeOk() (*int16, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *VmLogListOptions) SetCode(v int16) {
	o.Code = v
}

// GetFrom returns the From field value
func (o *VmLogListOptions) GetFrom() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetFromOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *VmLogListOptions) SetFrom(v int64) {
	o.From = v
}

// GetTo returns the To field value
func (o *VmLogListOptions) GetTo() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetToOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *VmLogListOptions) SetTo(v int64) {
	o.To = v
}

// GetTail returns the Tail field value
func (o *VmLogListOptions) GetTail() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Tail
}

// GetTailOk returns a tuple with the Tail field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetTailOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tail, true
}

// SetTail sets field value
func (o *VmLogListOptions) SetTail(v int32) {
	o.Tail = v
}

// GetHead returns the Head field value
func (o *VmLogListOptions) GetHead() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Head
}

// GetHeadOk returns a tuple with the Head field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetHeadOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Head, true
}

// SetHead sets field value
func (o *VmLogListOptions) SetHead(v int32) {
	o.Head = v
}

// GetReverse returns the Reverse field value
func (o *VmLogListOptions) GetReverse() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Reverse
}

// GetReverseOk returns a tuple with the Reverse field value
// and a boolean to check if the value has been set.
func (o *VmLogListOptions) GetReverseOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reverse, true
}

// SetReverse sets field value
func (o *VmLogListOptions) SetReverse(v bool) {
	o.Reverse = v
}

func (o VmLogListOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["class"] = o.Class
	toSerialize["code"] = o.Code
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["tail"] = o.Tail
	toSerialize["head"] = o.Head
	toSerialize["reverse"] = o.Reverse
	return toSerialize, nil
}

type NullableVmLogListOptions struct {
	value *VmLogListOptions
	isSet bool
}

func (v NullableVmLogListOptions) Get() *VmLogListOptions {
	return v.value
}

func (v *NullableVmLogListOptions) Set(val *VmLogListOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmLogListOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmLogListOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmLogListOptions(val *VmLogListOptions) *NullableVmLogListOptions {
	return &NullableVmLogListOptions{value: val, isSet: true}
}

func (v NullableVmLogListOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmLogListOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


