/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// OperationState result of an operation. PERSISTED, APPEND ONLY!
type OperationState int16

// List of operation_state
const (
	OPERATION_STARTED OperationState = 1
	OPERATION_FAILED OperationState = 2
	OPERATION_COMPLETED OperationState = 3
)

// All allowed values of OperationState enum
var AllowedOperationStateEnumValues = []OperationState{
	1,
	2,
	3,
}

func (v *OperationState) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OperationState(value)
	for _, existing := range AllowedOperationStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OperationState", value)
}

// NewOperationStateFromValue returns a pointer to a valid OperationState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOperationStateFromValue(v int16) (*OperationState, error) {
	ev := OperationState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OperationState: valid values are %v", v, AllowedOperationStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OperationState) IsValid() bool {
	for _, existing := range AllowedOperationStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to operation_state value
func (v OperationState) Ptr() *OperationState {
	return &v
}

type NullableOperationState struct {
	value *OperationState
	isSet bool
}

func (v NullableOperationState) Get() *OperationState {
	return v.value
}

func (v *NullableOperationState) Set(val *OperationState) {
	v.value = val
	v.isSet = true
}

func (v NullableOperationState) IsSet() bool {
	return v.isSet
}

func (v *NullableOperationState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperationState(val *OperationState) *NullableOperationState {
	return &NullableOperationState{value: val, isSet: true}
}

func (v NullableOperationState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperationState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

