/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VmCreateOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VmCreateOptions{}

// VmCreateOptions struct for VmCreateOptions
type VmCreateOptions struct {
	Vmdef Vmdef `json:"vmdef"`
	// Unique Identifier for VMs, Hosts, Networks; RFC 4122
	Host string `json:"host"`
}

type _VmCreateOptions VmCreateOptions

// NewVmCreateOptions instantiates a new VmCreateOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVmCreateOptions(vmdef Vmdef, host string) *VmCreateOptions {
	this := VmCreateOptions{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.Vmdef = vmdef
	this.Host = host
	return &this
}

// NewVmCreateOptionsWithDefaults instantiates a new VmCreateOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmCreateOptionsWithDefaults() *VmCreateOptions {
	this := VmCreateOptions{}
	return &this
}

// GetVmdef returns the Vmdef field value
func (o *VmCreateOptions) GetVmdef() Vmdef {
	if o == nil {
		var ret Vmdef
		return ret
	}

	return o.Vmdef
}

// GetVmdefOk returns a tuple with the Vmdef field value
// and a boolean to check if the value has been set.
func (o *VmCreateOptions) GetVmdefOk() (*Vmdef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vmdef, true
}

// SetVmdef sets field value
func (o *VmCreateOptions) SetVmdef(v Vmdef) {
	o.Vmdef = v
}

// GetHost returns the Host field value
func (o *VmCreateOptions) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *VmCreateOptions) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *VmCreateOptions) SetHost(v string) {
	o.Host = v
}

func (o VmCreateOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vmdef"] = o.Vmdef
	toSerialize["host"] = o.Host
	return toSerialize, nil
}

type NullableVmCreateOptions struct {
	value *VmCreateOptions
	isSet bool
}

func (v NullableVmCreateOptions) Get() *VmCreateOptions {
	return v.value
}

func (v *NullableVmCreateOptions) Set(val *VmCreateOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableVmCreateOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableVmCreateOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVmCreateOptions(val *VmCreateOptions) *NullableVmCreateOptions {
	return &NullableVmCreateOptions{value: val, isSet: true}
}

func (v NullableVmCreateOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVmCreateOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


