/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// DiskManMode disk management mode. Unmanaged just uses a disk as-is. Only virtual disks (NFS) can be managed, iSCSI LUNs are always unmanaged. A managed, non-existing disk will be created by vm_create, vm_update, a managed, existing disk will be claimed by vm_create, vm_update. 
type DiskManMode int16

// List of disk_man_mode
const (
	DISK_MAN_UNMANAGED DiskManMode = 0
	DISK_MAN_MANAGED DiskManMode = 1
)

// All allowed values of DiskManMode enum
var AllowedDiskManModeEnumValues = []DiskManMode{
	0,
	1,
}

func (v *DiskManMode) UnmarshalJSON(src []byte) error {
	var value int16
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DiskManMode(value)
	for _, existing := range AllowedDiskManModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DiskManMode", value)
}

// NewDiskManModeFromValue returns a pointer to a valid DiskManMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDiskManModeFromValue(v int16) (*DiskManMode, error) {
	ev := DiskManMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DiskManMode: valid values are %v", v, AllowedDiskManModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DiskManMode) IsValid() bool {
	for _, existing := range AllowedDiskManModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to disk_man_mode value
func (v DiskManMode) Ptr() *DiskManMode {
	return &v
}

type NullableDiskManMode struct {
	value *DiskManMode
	isSet bool
}

func (v NullableDiskManMode) Get() *DiskManMode {
	return v.value
}

func (v *NullableDiskManMode) Set(val *DiskManMode) {
	v.value = val
	v.isSet = true
}

func (v NullableDiskManMode) IsSet() bool {
	return v.isSet
}

func (v *NullableDiskManMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiskManMode(val *DiskManMode) *NullableDiskManMode {
	return &NullableDiskManMode{value: val, isSet: true}
}

func (v NullableDiskManMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiskManMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

