/*
virtx

This is a simple virtualization API for a KVM Cluster. All fields are marked as required for simplicity and to avoid bad code generator results. Where possible, an integer value of 0 means \"unset\", \"unused\" or \"default\". In the rare cases where this clashes with a valid 0 value, the value -1 is used instead. For strings, the convention is that the \"\" (empty string) means \"unset\", \"unused\" or \"default\". 

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MigrationInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MigrationInfo{}

// MigrationInfo struct for MigrationInfo
type MigrationInfo struct {
	State MigrationState `json:"state"`
	Progress TransferProgress `json:"progress"`
}

type _MigrationInfo MigrationInfo

// NewMigrationInfo instantiates a new MigrationInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMigrationInfo(state MigrationState, progress TransferProgress) *MigrationInfo {
	this := MigrationInfo{}
    // XXX these two lines are here to silence errors about unused imports
    var _ = fmt.Println
    var _ = bytes.NewBuffer

	this.State = state
	this.Progress = progress
	return &this
}

// NewMigrationInfoWithDefaults instantiates a new MigrationInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMigrationInfoWithDefaults() *MigrationInfo {
	this := MigrationInfo{}
	return &this
}

// GetState returns the State field value
func (o *MigrationInfo) GetState() MigrationState {
	if o == nil {
		var ret MigrationState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *MigrationInfo) GetStateOk() (*MigrationState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *MigrationInfo) SetState(v MigrationState) {
	o.State = v
}

// GetProgress returns the Progress field value
func (o *MigrationInfo) GetProgress() TransferProgress {
	if o == nil {
		var ret TransferProgress
		return ret
	}

	return o.Progress
}

// GetProgressOk returns a tuple with the Progress field value
// and a boolean to check if the value has been set.
func (o *MigrationInfo) GetProgressOk() (*TransferProgress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Progress, true
}

// SetProgress sets field value
func (o *MigrationInfo) SetProgress(v TransferProgress) {
	o.Progress = v
}

func (o MigrationInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	toSerialize["progress"] = o.Progress
	return toSerialize, nil
}

type NullableMigrationInfo struct {
	value *MigrationInfo
	isSet bool
}

func (v NullableMigrationInfo) Get() *MigrationInfo {
	return v.value
}

func (v *NullableMigrationInfo) Set(val *MigrationInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableMigrationInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableMigrationInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMigrationInfo(val *MigrationInfo) *NullableMigrationInfo {
	return &NullableMigrationInfo{value: val, isSet: true}
}

func (v NullableMigrationInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMigrationInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


