/*
virtx

This is a simple virtualization API for a KVM Cluster

API version: 0.0.1
Contact: claudio.fontana@suse.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Cpudef type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Cpudef{}

// Cpudef struct for Cpudef
type Cpudef struct {
	// libvirt cpu model
	Model *string `json:"model,omitempty"`
	// number of sockets (NUMA)
	Sockets *int32 `json:"sockets,omitempty"`
	// number of cores per socket
	Cores *int32 `json:"cores,omitempty"`
	// number of threads per core
	Threads *int32 `json:"threads,omitempty"`
}

// NewCpudef instantiates a new Cpudef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCpudef() *Cpudef {
	this := Cpudef{}
	return &this
}

// NewCpudefWithDefaults instantiates a new Cpudef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCpudefWithDefaults() *Cpudef {
	this := Cpudef{}
	return &this
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *Cpudef) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cpudef) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *Cpudef) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *Cpudef) SetModel(v string) {
	o.Model = &v
}

// GetSockets returns the Sockets field value if set, zero value otherwise.
func (o *Cpudef) GetSockets() int32 {
	if o == nil || IsNil(o.Sockets) {
		var ret int32
		return ret
	}
	return *o.Sockets
}

// GetSocketsOk returns a tuple with the Sockets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cpudef) GetSocketsOk() (*int32, bool) {
	if o == nil || IsNil(o.Sockets) {
		return nil, false
	}
	return o.Sockets, true
}

// HasSockets returns a boolean if a field has been set.
func (o *Cpudef) HasSockets() bool {
	if o != nil && !IsNil(o.Sockets) {
		return true
	}

	return false
}

// SetSockets gets a reference to the given int32 and assigns it to the Sockets field.
func (o *Cpudef) SetSockets(v int32) {
	o.Sockets = &v
}

// GetCores returns the Cores field value if set, zero value otherwise.
func (o *Cpudef) GetCores() int32 {
	if o == nil || IsNil(o.Cores) {
		var ret int32
		return ret
	}
	return *o.Cores
}

// GetCoresOk returns a tuple with the Cores field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cpudef) GetCoresOk() (*int32, bool) {
	if o == nil || IsNil(o.Cores) {
		return nil, false
	}
	return o.Cores, true
}

// HasCores returns a boolean if a field has been set.
func (o *Cpudef) HasCores() bool {
	if o != nil && !IsNil(o.Cores) {
		return true
	}

	return false
}

// SetCores gets a reference to the given int32 and assigns it to the Cores field.
func (o *Cpudef) SetCores(v int32) {
	o.Cores = &v
}

// GetThreads returns the Threads field value if set, zero value otherwise.
func (o *Cpudef) GetThreads() int32 {
	if o == nil || IsNil(o.Threads) {
		var ret int32
		return ret
	}
	return *o.Threads
}

// GetThreadsOk returns a tuple with the Threads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Cpudef) GetThreadsOk() (*int32, bool) {
	if o == nil || IsNil(o.Threads) {
		return nil, false
	}
	return o.Threads, true
}

// HasThreads returns a boolean if a field has been set.
func (o *Cpudef) HasThreads() bool {
	if o != nil && !IsNil(o.Threads) {
		return true
	}

	return false
}

// SetThreads gets a reference to the given int32 and assigns it to the Threads field.
func (o *Cpudef) SetThreads(v int32) {
	o.Threads = &v
}

func (o Cpudef) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Cpudef) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.Sockets) {
		toSerialize["sockets"] = o.Sockets
	}
	if !IsNil(o.Cores) {
		toSerialize["cores"] = o.Cores
	}
	if !IsNil(o.Threads) {
		toSerialize["threads"] = o.Threads
	}
	return toSerialize, nil
}

type NullableCpudef struct {
	value *Cpudef
	isSet bool
}

func (v NullableCpudef) Get() *Cpudef {
	return v.value
}

func (v *NullableCpudef) Set(val *Cpudef) {
	v.value = val
	v.isSet = true
}

func (v NullableCpudef) IsSet() bool {
	return v.isSet
}

func (v *NullableCpudef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCpudef(val *Cpudef) *NullableCpudef {
	return &NullableCpudef{value: val, isSet: true}
}

func (v NullableCpudef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCpudef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


